### PR TITLE
MSGFPlusAdapter sets MS-GF+ e-value as peptide score

### LINKED ISSUE #1691: Suboptimal score selected in MSGFPlusAdapter
The `MSGFPlusAdapter` now uses internally a direct conversion from the MS-GF+ output format `mzid` to `idXML`. The scores are incorrectly imported. That leads in a standard `MSGFPlusAdapter/PeptideIndexer/IDPosteriorErrorProbability` workflow to the following `IDPosteriorErrorProbability` crash.
```
No data collected. Check whether search engine is supported.
```
See earlier discussion here https://github.com/OpenMS/OpenMS/pull/1679#issuecomment-153070360 and the following example `idXML` file.
https://gist.github.com/lars20070/cbcd3f0f623b2be074b7

### PR DESCRIPTION
**Pull request by lars20070**
Since #1679, the MS-GF+ adapter converts `mzid` directly to `idXML`. The `mzid` handler sets `MS:1002049` (MS-GF raw score) as peptide identification score.

The `MSGFPlusAdapter` now re-sets the peptide identification score to `MS:1002052` (MS-GF spectral E-value) after the `mzid` to `idXML` conversion. Fixes #1691.

### CODE REVIEW

File: src/topp/MSGFPlusAdapter.cpp [hunk 1]
```diff
@@ -388,6 +388,31 @@ class MSGFPlusAdapter :
...
+  {
+    return "peptide hit with sequence '" + hit.getSequence().toString() +
+      "', charge " + String(hit.getCharge()) + ", score " + 
+      String(hit.getScore());
+  }
+
+  // Set the MS-GF+ e-value (MS:1002052) as new peptide identification score.
+  void switchScores_(PeptideIdentification& id)
+  {
+    for (vector<PeptideIdentification::HitType>::iterator hit_it = id.getHits().begin(); hit_it != id.getHits().end(); ++hit_it)
```
Comment (hendrikweisser) [inline src/topp/MSGFPlusAdapter.cpp]: Just use `vector<PeptideHit>`, since there's no template here.

File: src/topp/MSGFPlusAdapter.cpp [hunk 2]
```diff
@@ -722,6 +747,11 @@ class MSGFPlusAdapter :
         vector<ProteinIdentification> protein_ids;
         vector<PeptideIdentification> peptide_ids;
         MzIdentMLFile().load(mzid_temp, protein_ids, peptide_ids);
+        // set the MS-GF+ e-value as new peptide identification score
```
Comment (hendrikweisser) [inline src/topp/MSGFPlusAdapter.cpp]: "spectral E-value" - to avoid confusion with the other (peptide-level?) E-value that is reported by MS-GF+

File: src/topp/MSGFPlusAdapter.cpp [hunk 3]
```diff
@@ -388,6 +388,31 @@ class MSGFPlusAdapter :
...
+      // MS:1002052 == MS-GF spectral E-value
+      if (!hit_it->metaValueExists("MS:1002052"))
+      {
+        String msg = "Meta value 'MS:1002052' not found for " + describeHit_(*hit_it);
+        throw Exception::MissingInformation(__FILE__, __LINE__, __PRETTY_FUNCTION__, msg);
+      }
+      
+      hit_it->setScore(hit_it->getMetaValue("MS:1002052"));
+    }
+    id.setScoreType("MSGFPlus");
```
Comment (hendrikweisser) [inline src/topp/MSGFPlusAdapter.cpp]: I think the score type should be "SpecEValue", as in line 681 (old code)/706 (your code).

File: src/tests/topp/THIRDPARTY/MSGFPlusAdapter_1_out.idXML [hunk 4]
```diff
@@ -32,8 +32,8 @@
 			</ProteinHit>
 			<UserParam type="string" name="spectra_data" value="/home/lars/Desktop/tests/THIRDPARTY/spectra.mzML"/>
 		</ProteinIdentification>
-		<PeptideIdentification score_type="MS-GF:RawScore" higher_score_better="true" significance_threshold="0" MZ="1063.20983886719" RT="4587.6689453125" spectrum_reference="spectrum=1" >
-			<PeptideHit score="163" sequence="IALSRPNVEVVALNDPFITNDYAAYM(Oxidation)FK" charge="3" aa_before="-" aa_after="E" protein_refs="PH_1" >
+		<PeptideIdentification score_type="MSGFPlus" higher_score_better="false" significance_threshold="0" MZ="1063.20983886719" RT="4587.6689453125" spectrum_reference="spectrum=1" >
```
Comment (hendrikweisser) [inline src/tests/topp/THIRDPARTY/MSGFPlusAdapter_1_out.idXML]: See my comment about the score type in the MSGFPlusAdapter code.

**Comment by hendrikweisser** [comment]
Thanks for taking care of this, Lars!
See my comments on the diff, otherwise it looks good.

**Comment by lars20070** [comment]
Good points @hendrikweisser. Thanks.
