### PR TITLE
[FIX]suppressing warning toSet() is deprecated

### LINKED ISSUE #5937: warning: `QSet<T> QList<T>::toSet()` is deprecated
```shell
/home/USER/Development/OpenMs/src/openms_gui/source/VISUAL/MISC/FilterableList.cpp: In member function ‘void OpenMS::Internal::FilterableList::setBlacklistItems(const QStringList&)’:
/home/USER/Development/OpenMs/src/openms_gui/source/VISUAL/MISC/FilterableList.cpp:72:34: warning: ‘QSet<T> QList<T>::toSet() const [with T = QString]’ is deprecated: Use QSet<T>(list.begin(), list.end()) instead. [-Wdeprecated-declarations]
   72 |       blacklist_ = bl_items.toSet();
      |                    ~~~~~~~~~~~~~~^~
In file included from /usr/include/qt/QtCore/qhash.h:46,
                 from /usr/include/qt/QtCore/qset.h:43,
                 from /usr/include/qt/QtCore/QSet:1,
                 from /home/USER/Development/OpenMs/src/openms_gui/include/OpenMS/VISUAL/MISC/FilterableList.h:39,
                 from /home/USER/Development/OpenMs/src/openms_gui/source/VISUAL/MISC/FilterableList.cpp:35:
/usr/include/qt/QtCore/qlist.h:413:13: note: declared here
  413 |     QSet<T> toSet() const;
      |             ^~~~~
```

### PR DESCRIPTION
**Pull request by Amit0617**
# Description

Please include a summary of the change and which issue is fixed.
Fixes #5937 
# Checklist:
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.
- Or click on the action: e.g., for clang-format linting

# Note:
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

# Advanced commands (admins / reviewer only):
- `/rebase` will try to rebase the PR on the current develop branch.
- `/reformat` (experimental) applies the clang-format style changes as additional commit
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds

### CODE REVIEW

File: src/openms_gui/source/VISUAL/MISC/FilterableList.cpp [hunk 1]
```diff
@@ -69,20 +69,38 @@ namespace OpenMS
...
+#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
       blacklist_ = bl_items.toSet();
+#pragma GCC diagnostic pop
       updateInternalList_();
     }
 
     void FilterableList::addBlackListItems(const QStringList& items)
     {
+      /*
+       * Suppressing warning toSet() deprecated till Qt 5.14
```
Comment (timosachsenberg) [inline src/openms_gui/source/VISUAL/MISC/FilterableList.cpp:85]: this is not toSet()

Comment (Amit0617) [reply src/openms_gui/source/VISUAL/MISC/FilterableList.cpp:85]: And I have done for only those lines against which compiler was warning

Comment (timosachsenberg) [reply src/openms_gui/source/VISUAL/MISC/FilterableList.cpp:85]: sorry my bad :P

**Review by timosachsenberg — APPROVED** [review]
