### PR TITLE
[FIX] isnan error

### LINKED ISSUE #5864: error: 'isnan' was not declared in this scope
Hi all.

`OpenMS-2.8.0` is failing with `GCC-12.0.1`:

```
[ 92%] Building CXX object src/openms/CMakeFiles/OpenMS.dir/source/QC/MQEvidenceExporter.cpp.o
cd /builddir/build/BUILD/OpenMS-2.8.0/build/src/openms && /usr/bin/g++ -DBOOST_ALL_NO_LIB -DOpenMS_EXPORTS -DQT_CORE_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_SQL_LIB -I/builddir/build/BUILD/OpenMS-2.8.0/build/src/openms -I/builddir/build/BUILD/OpenMS-2.8.0/src/openms -I/builddir/build/BUILD/OpenMS-2.8.0/build/src/openms/OpenMS_autogen/include -I/builddir/build/BUILD/OpenMS-2.8.0/src/openms/include -I/builddir/build/BUILD/OpenMS-2.8.0/build/src/openms/include -I/builddir/build/BUILD/OpenMS-2.8.0/src/openswathalgo/include -I/builddir/build/BUILD/OpenMS-2.8.0/build/src/openswathalgo/include -I/builddir/build/BUILD/OpenMS-2.8.0/src/openswathalgo/thirdparty/MIToolbox/include -I/builddir/build/BUILD/OpenMS-2.8.0/src/openswathalgo/thirdparty/MIToolbox/src -isystem /builddir/build/BUILD/OpenMS-2.8.0/src/openms/thirdparty/eol-bspline -isystem /builddir/build/BUILD/OpenMS-2.8.0/src/openms/thirdparty/IsoSpec -isystem /builddir/build/BUILD/OpenMS-2.8.0/src/openms/thirdparty/json -isystem /builddir/build/BUILD/OpenMS-2.8.0/src/openms/thirdparty/evergreen/src -isystem /usr/include/libsvm -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtSql -isystem /usr/include/WildMagic -isystem /usr/include/eigen3 -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -Wno-cpp -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -Wno-non-virtual-dtor -Wno-unknown-pragmas -Wno-long-long -Wno-unused-function -Wno-variadic-macros -fPIC -fopenmp -MD -MT src/openms/CMakeFiles/OpenMS.dir/source/QC/MQEvidenceExporter.cpp.o -MF CMakeFiles/OpenMS.dir/source/QC/MQEvidenceExporter.cpp.o.d -o CMakeFiles/OpenMS.dir/source/QC/MQEvidenceExporter.cpp.o -c /builddir/build/BUILD/OpenMS-2.8.0/src/openms/source/QC/MQEvidenceExporter.cpp
make[3]: Leaving directory '/builddir/build/BUILD/OpenMS-2.8.0/build'
In file included from /builddir/build/BUILD/OpenMS-2.8.0/src/openms/include/OpenMS/KERNEL/MSExperiment.h:39,
                 from /builddir/build/BUILD/OpenMS-2.8.0/src/openms/include/OpenMS/KERNEL/ConsensusMap.h:41,
                 from /builddir/build/BUILD/OpenMS-2.8.0/src/openms/include/OpenMS/QC/MQEvidenceExporter.h:39,
                 from /builddir/build/BUILD/OpenMS-2.8.0/src/openms/source/QC/MQEvidenceExporter.cpp:35:
/builddir/build/BUILD/OpenMS-2.8.0/src/openms/include/OpenMS/KERNEL/AreaIterator.h:58:19: warning: 'template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator' is deprecated [-Wdeprecated-declarations]
   58 |       public std::iterator<std::forward_iterator_tag, ValueT>
      |                   ^~~~~~~~
In file included from /usr/include/c++/12/string:45,
                 from /usr/include/c++/12/bits/locale_classes.h:40,
                 from /usr/include/c++/12/bits/ios_base.h:41,
                 from /usr/include/c++/12/ios:42,
                 from /usr/include/c++/12/istream:38,
                 from /usr/include/c++/12/fstream:38,
                 from /builddir/build/BUILD/OpenMS-2.8.0/src/openms/include/OpenMS/QC/MQEvidenceExporter.h:37:
/usr/include/c++/12/bits/stl_iterator_base_types.h:127:34: note: declared here
  127 |     struct _GLIBCXX17_DEPRECATED iterator
      |                                  ^~~~~~~~
/builddir/build/BUILD/OpenMS-2.8.0/src/openms/source/QC/MQEvidenceExporter.cpp: In member function 'void MQEvidence::exportRowFromFeature_(const OpenMS::Feature&, const OpenMS::ConsensusMap&, OpenMS::Size, const OpenMS::String&, const std::multimap<OpenMS::String, std::pair<long unsigned int, long unsigned int> >&, const OpenMS::ProteinIdentification::Mapping&)':
/builddir/build/BUILD/OpenMS-2.8.0/src/openms/source/QC/MQEvidenceExporter.cpp:318:7: error: 'isnan' was not declared in this scope
  318 |   if (isnan(uncalibrated_mz_error_ppm) && isnan(calibrated_mz_error_ppm))
      |       ^~~~~
/builddir/build/BUILD/OpenMS-2.8.0/src/openms/source/QC/MQEvidenceExporter.cpp:318:7: note: suggested alternatives:
In file included from /builddir/build/BUILD/OpenMS-2.8.0/src/openms/include/OpenMS/DATASTRUCTURES/ListUtils.h:42,
                 from /builddir/build/BUILD/OpenMS-2.8.0/src/openms/include/OpenMS/DATASTRUCTURES/DataValue.h:38,
                 from /builddir/build/BUILD/OpenMS-2.8.0/src/openms/include/OpenMS/METADATA/MetaInfoInterface.h:41,
                 from /builddir/build/BUILD/OpenMS-2.8.0/src/openms/include/OpenMS/KERNEL/RichPeak2D.h:38,
                 from /builddir/build/BUILD/OpenMS-2.8.0/src/openms/include/OpenMS/KERNEL/BaseFeature.h:37,
                 from /builddir/build/BUILD/OpenMS-2.8.0/src/openms/include/OpenMS/KERNEL/ConsensusFeature.h:38,
                 from /builddir/build/BUILD/OpenMS-2.8.0/src/openms/include/OpenMS/QC/MQEvidenceExporter.h:38:
/usr/include/c++/12/cmath:632:5: note:   'std::isnan'
  632 |     isnan(_Tp __x)
      |     ^~~~~
In file included from /builddir/build/BUILD/OpenMS-2.8.0/src/openms/source/QC/MQEvidenceExporter.cpp:44:
/usr/include/boost/math/special_functions/fpclassify.hpp:605:14: note:   'boost::math::isnan'
  605 | inline bool (isnan)(T x)
      |              ^~~~~
make[3]: *** [src/openms/CMakeFiles/OpenMS.dir/build.make:9183: src/openms/CMakeFiles/OpenMS.dir/source/QC/MQEvidenceExporter.cpp.o] Error 1
```

### PR DESCRIPTION
**Pull request by Amit0617**
# Description

Please include a summary of the change and which issue is fixed.
fix #5864 

# Checklist:
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.
- Or click on the action: e.g., for clang-format linting

# Note:
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

# Advanced commands (admins / reviewer only):
- `/rebase` will try to rebase the PR on the current develop branch.
- `/reformat` (experimental) applies the clang-format style changes as additional commit
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds

### CODE REVIEW

File: src/openms/source/QC/MQEvidenceExporter.cpp [hunk 1]
```diff
@@ -41,10 +41,10 @@
 #include <OpenMS/SYSTEM/File.h>
 
 #include <QtCore/QDir>
-#include <boost/math/special_functions/fpclassify.hpp> // isnan
+#include <cmath> // isnan
 #include <fstream>
 
-#include <boost/math/special_functions/fpclassify.hpp> // isnan
+#include <cmath> // isnan
```
Comment (timosachsenberg) [inline src/openms/source/QC/MQEvidenceExporter.cpp:47]: duplicate include

**Review by timosachsenberg — APPROVED** [review]

**Comment by timosachsenberg** [comment]
thanks!
