### PR TITLE
FIX: Python Bindings SiriusAdapter

### LINKED ISSUE #5184: Segmentation fault (core dumped)
Hi,

I am trying to load mzML files with 500MB approximate size and I am constantly getting this segmentation fault error. However, when I use smaller files, this doesn't occur and my workflow runs as it is supposed to. This is not a memory issue since I am using a machine that has a lot of space. Is this a c++ error? 

import numpy as np
import pandas as pd
import pyopenms
from pyopenms import *

exp = MSExperiment()

import sys
print("Loading")
MzMLFile().load(sys.argv[1], exp)
print("Loaded")

### PR DESCRIPTION
**Pull request by oliveralka**
# Description
fixes  #5184

Issue: SIRIUSAdapter::store failed in pyopenms. 
The problem was that the BaseFeature* tried to access memory, which was altered by copying the FeatureMap internally in cython to read and write a python list. 
This was fixed by adding an additional class to wrap the vector<FeatureMap> and the KDTreeMaps. 

Also added a POSTCONDITION if the output directory of SIRIUS  is empty. 

# Checklist:
- [x] Make sure that you are listed in the AUTHORS file
- [x] Add relevant changes and new features to the CHANGELOG file
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes
- [x] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.

### CODE REVIEW

**Comment by oliveralka** [comment]
rebuild jenkins

File: src/openms/include/OpenMS/ANALYSIS/MAPMATCHING/FeatureMapping.h [hunk 1]
```diff
@@ -45,9 +46,17 @@ namespace OpenMS
       {
           public:
 
-          struct FeatureToMs2Indices
+          class FeatureMappingInfo
           {
-             Map<const BaseFeature*, std::vector<size_t>> assignedMS2;
+          public:
+            std::vector<FeatureMap> v_fp;
```
Comment (timosachsenberg) [inline src/openms/include/OpenMS/ANALYSIS/MAPMATCHING/FeatureMapping.h:52]: please add documentation and some description. 
maybe rename the variables to something more telling.
std::vector<FeatureMap> feature_maps; // the actual feature data
KDTreeFeatureMaps kd_tree; // kdTree references into feature_maps and provides fast spatial queries

File: src/openms/source/ANALYSIS/ID/SiriusAdapterAlgorithm.cpp [hunk 2]
```diff
@@ -508,12 +506,12 @@ namespace OpenMS
                                   });
           feature_map.erase(map_it, feature_map.end());
   
-          v_fp.push_back(feature_map);
-          fp_map_kd.addMaps(v_fp);
+          fm_info.v_fp.push_back(feature_map);
+          fm_info.fp_map_kd.addMaps(fm_info.v_fp);
```
Comment (timosachsenberg) [inline src/openms/source/ANALYSIS/ID/SiriusAdapterAlgorithm.cpp:510]: add comment that kDTree references into feature_map

**Comment by timosachsenberg** [comment]
good job in finding a solution 👍

**Comment by oliveralka** [comment]
Thanks for the help with spotting the error! 👍

File: src/openms/include/OpenMS/ANALYSIS/MAPMATCHING/FeatureMapping.h [hunk 3]
```diff
@@ -45,9 +46,19 @@ namespace OpenMS
       {
           public:
 
-          struct FeatureToMs2Indices
+          /// Stores information required for preprocessing
+          class FeatureMappingInfo
```
Comment (KyowonJeong) [inline src/openms/include/OpenMS/ANALYSIS/MAPMATCHING/FeatureMapping.h:50]: Well, this might not be a comment from a reviewer, but I am still confused why sometimes I use class and other structure.

File: src/openms/source/FORMAT/DATAACCESS/SiriusMzTabWriter.cpp [hunk 4]
```diff
@@ -72,10 +72,10 @@ String SiriusMzTabWriter::extractFeatureId(const String& path)
   return feature_id;
 }
 
-std::map< String, Size > SiriusMzTabWriter::extract_columnname_to_columnindex(CsvFile& csvfile)
+std::map< std::string, Size > SiriusMzTabWriter::extract_columnname_to_columnindex(CsvFile& csvfile)
 {
   StringList header_row;
-  std::map< String, Size > columnname_to_columnindex;
+  std::map< std::string, Size > columnname_to_columnindex;
```
Comment (KyowonJeong) [inline src/openms/source/FORMAT/DATAACCESS/SiriusMzTabWriter.cpp:78]: I have been using String. Should I change them to std::string as well? I will.

**Review by KyowonJeong — COMMENTED** [review]
Looks OK! (as far as my humble review ability concerned)...

File: src/openms/source/FORMAT/DATAACCESS/SiriusMzTabWriter.cpp (hunk 4 above)
Comment (timosachsenberg) [reply src/openms/source/FORMAT/DATAACCESS/SiriusMzTabWriter.cpp:78]: In practice not that important I guess. I try to use std::string whenever it is sufficient.

File: src/openms/include/OpenMS/ANALYSIS/MAPMATCHING/FeatureMapping.h (hunk 3 above)
Comment (timosachsenberg) [reply src/openms/include/OpenMS/ANALYSIS/MAPMATCHING/FeatureMapping.h:50]: There are no clear rules but in general it is good to use structs for simple records / PODs and switch to class if you have e.g. private or protected members.
See e.g., with some hints when not to use class 
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c-classes-and-class-hierarchies for suggestions how to use them.

File: src/openms/source/FORMAT/DATAACCESS/SiriusMzTabWriter.cpp (hunk 4 above)
Comment (oliveralka) [reply src/openms/source/FORMAT/DATAACCESS/SiriusMzTabWriter.cpp:78]: Using `std::string` instead of `OpenMS::String` in the map is due to pyopenms wrapping. In general, you can use `OpenMS::String` without an issue:

```
Most complex STL constructs can be wrapped even if they are nested, however mixing them with user-defined types does not always work, see Limitations below. Nested std::vector constructs work well even with user-defined (OpenMS-defined) types. However, std::map<String, X> does not work (since String is user-defined, however, a primitive C++ type such as std::map<std::string, X> would work).
```
https://pyopenms.readthedocs.io/en/latest/wrap_classes.html

**Comment by oliveralka** [comment]
rebuild jenkins

File: src/openms/include/OpenMS/ANALYSIS/MAPMATCHING/FeatureMapping.h (hunk 3 above)
Comment (oliveralka) [reply src/openms/include/OpenMS/ANALYSIS/MAPMATCHING/FeatureMapping.h:50]: I have to admit that here it was simply personal preference, this could also be a struct.

**Comment by oliveralka** [comment]
Since the PR was not merged yet, I added fix for the db parameter, since multiple databases are allowed.
The can now be specified as string "db1,db2,db3" - see #5255

**Review by KyowonJeong — APPROVED** [review]
The new changes looks fine!! Thanks!
