### PR TITLE
trim .* from file extension in toppview

### LINKED ISSUE #7779: TOPPView run tool on visible area
11:02:55 ERROR: Cannot create temporary file
Cannot write to 'C:/Users/sachs/AppData/Local/Temp/TOPPView_20241218_110237_sachsenberg_10432_148_out.*.featureXML'!

probably related to FileHandler chagne

### PR DESCRIPTION
**Pull request by poshul**
## Description

try to fix https://github.com/OpenMS/OpenMS/issues/7779

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.seqan.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

File: src/openms_gui/source/VISUAL/DIALOGS/ToolsDialog.cpp [hunk 1]
```diff
@@ -446,13 +446,23 @@ namespace OpenMS
...
+    else 
     {
-      QMessageBox::critical(this, "Error", QString("Error determining output type from tool. Tool is not compatible with TOPPView"));
+      // If we have no valid types, produce an error
+      if (validStrings.empty())
+        {
+          QMessageBox::critical(this, "Error", QString("Error determining output type from tool. Tool is not compatible with TOPPView"));
+        }
+          // If we have multiple valid output types, we don't know what the file actually contains, so use UNKNOWN
+
```
Comment (cbielow) [inline src/openms_gui/source/VISUAL/DIALOGS/ToolsDialog.cpp:465]: there is something missing here?!

**Review by cbielow — CHANGES_REQUESTED** [review]

File: src/openms_gui/source/VISUAL/DIALOGS/ToolsDialog.cpp (hunk 1 above)
Comment (cbielow) [reply src/openms_gui/source/VISUAL/DIALOGS/ToolsDialog.cpp:465]: we could also (as a precaution) emit a warning message when we detect multiple extensions and print something like
```
Multiple possible output aure supported by the tool. You probably need to set the output type in the parameters (usually `out_type`).
```
to the log window

Comment (poshul) [reply src/openms_gui/source/VISUAL/DIALOGS/ToolsDialog.cpp:465]: > ?!

Nope. We set extension to UNKNOWN above, so we don't need to do anything here. Just putting a comment in so that the logic flow is clear.

Comment (poshul) [reply src/openms_gui/source/VISUAL/DIALOGS/ToolsDialog.cpp:465]: > we could also (as a precaution) emit a warning message when we detect multiple extensions and print something like
> 
> ```
> Multiple possible output aure supported by the tool. You probably need to set the output type in the parameters (usually `out_type`).
> ```
> 
> to the log window

I'm merging this now since it's actively a problem for the work Timo is doing. I'll open another PR with the suggestion.

Comment (poshul) [reply src/openms_gui/source/VISUAL/DIALOGS/ToolsDialog.cpp:465]: see https://github.com/OpenMS/OpenMS/pull/7785/
