### PR TITLE
[TOPPView] Use copy of local member parent for showing About dialog

### LINKED ISSUE #5483: TOPPView: opening about from menu crashes

### LINKED ISSUE #5484: TOPPView macOS: Preferences do not work
On macOS you only have one slot in the preferences. Currently, this is occupied by the Layer preferences.
This also means initially they are greyed out until you load a dataset.
Global settings are missing completely.

### PR DESCRIPTION
**Pull request by jpfeuffer**
Fixes #5483

Fixes #5484

### CODE REVIEW

**Review by timosachsenberg — APPROVED** [review]

File: src/openms_gui/source/VISUAL/TOPPViewMenu.cpp [hunk 1]
```diff
@@ -90,7 +90,17 @@ namespace OpenMS
     m_file->addMenu(recent_files->getMenu()); // updates automatically via RecentFilesMenu class, since this is just a pointer
 
     m_file->addSeparator();
-    m_file->addAction("&Preferences", parent, &TOPPViewBase::preferencesDialog);
+    
+    //Specifically set the role of the Preferences item. Additionally we have to avoid adding other action items that are
+    // called preferences/config/options and have the default TextHeuristicRole because otherwise they will overwrite the macOS specific
+    // menu entry under Application -> Preferences...
+    //m_file->addAction("&Preferences", parent, &TOPPViewBase::preferencesDialog);
```
Comment (cbielow) [inline src/openms_gui/source/VISUAL/TOPPViewMenu.cpp:97]: AFAIK `addAction` returns a `QAction*` on which you can operate
thus you can shorten to

```
auto pref = m_file->addAction("&Preferences", parent, &TOPPViewBase::preferencesDialog);
pref->setMenuRole(QAction::PreferencesRole);
pref->setEnabled(true);
```
?

**Review by cbielow — CHANGES_REQUESTED** [review]
looks good.
Just a suggestion to make it more compact
