### PR TITLE
Fix duplicated parameters

### LINKED ISSUE #6628: PercolatorAdapter. Bug in usage message.
Issuing the command `PercolatorAdapter --helphelp` produces the expected message.

However, doing so in v2.8.0 produces two conflicting instructions for using `-post-processing-tdc`.

    -post_processing_tdc <value>                 Use target-decoy competition to assign q-values and PEPs. (default: 'true' valid: 'true', 'false')
    -post_processing_tdc                         Use target-decoy competition to assign q-values and PEPs.

### PR DESCRIPTION
**Pull request by cbielow**
## Description

Fixes  #6628, among two other potentially affected tools.

This is how I found them
```
  void TOPPBase::validateParameterSet_() const
  {
    std::set<String> all;
    for (const ParameterInformation& p : parameters_)
    {
      auto [it, was_newly_inserted] = all.emplace(p.name);
      if (!was_newly_inserted)
      {
        if (!p.name.empty()) throw Exception::InternalToolError(__FILE__, __LINE__, OPENMS_PRETTY_FUNCTION, "Parameter '" + p.name + "' already present!");
      }
    }
  }
```

but this code should 1) go into a dedicated class for dealing with ParameterInformation (and not in TOPPView in particular -- its way to big already) 2) currently chokes on two tools (e.g. `FeatureFinderIdentification`), which pull in tool parameters to the TOPP level, and thus create a duplicated `debug` option. There is no quick fix for this (other than ignoring the debug option for now or manually deleting and updating the offending parameters), so I will not include the checking code for now.

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

File: src/topp/PercolatorAdapter.cpp [hunk 1]
```diff
@@ -303,8 +303,6 @@ class PercolatorAdapter :
     registerInputFile_("fasta", "<file>", "", "Provide the fasta file as the argument to this flag, which will be used for protein grouping based on an in-silico digest (only valid if option -protein_level_fdrs is active).", !is_required, is_advanced_option);
     setValidFormats_("fasta", ListUtils::create<String>("FASTA"));
     registerStringOption_("decoy_pattern", "<value>", "random", "Define the text pattern to identify the decoy proteins and/or PSMs, set this up if the label that identifies the decoys in the database is not the default (Only valid if option -protein_level_fdrs is active).", !is_required, is_advanced_option);
-    registerStringOption_("post_processing_tdc", "<value>", "true", "Use target-decoy competition to assign q-values and PEPs.", !is_required, is_advanced_option);
```
Comment (timosachsenberg) [inline src/topp/PercolatorAdapter.cpp:306]: this changes the default from using target decoy competition to not using it!

Comment (timosachsenberg) [reply src/topp/PercolatorAdapter.cpp:306]: my guess is that it was changed to string to make it default and then some merge got the flag back in

Comment (cbielow) [reply src/topp/PercolatorAdapter.cpp:306]: no it does not.
The current (and old!) behavior is that the default is dictated by the `post_processing_tdc` flag (which is `false`).
So my fix merely makes the default behaviour more clear.
The default value of the string option was ignored -- this never worked as far as I can tell.

File: src/tests/topp/THIRDPARTY/PercolatorAdapter_1_out.idXML [hunk 2]
```diff
@@ -40,7 +40,7 @@
 				<UserParam type="int" name="Percolator:klammer" value="0"/>
 				<UserParam type="string" name="Percolator:fasta" value=""/>
 				<UserParam type="string" name="Percolator:decoy_pattern" value="random"/>
-				<UserParam type="string" name="Percolator:post_processing_tdc" value="false"/>
```
Comment (timosachsenberg) [inline src/tests/topp/THIRDPARTY/PercolatorAdapter_1_out.idXML:43]: but why is here the string parameter?

File: src/topp/PercolatorAdapter.cpp (hunk 1 above)
Comment (timosachsenberg) [reply src/topp/PercolatorAdapter.cpp:306]: hmm right. but seems that intention was to make it default:
https://github.com/OpenMS/OpenMS/pull/4895
https://github.com/OpenMS/OpenMS/pull/3646

I am just a bit worried that this could break some workflows that already exist

Comment (cbielow) [reply src/topp/PercolatorAdapter.cpp:306]: should not break anything since passing
` -post_processing_tdc true` on the current develop (before this PR) yields

`Trailing text argument(s) '[true]' given. Aborting!`

This means the string param could not have been used by anyone.
If someone set the parameter in an INI file, it would not lead to a crash, but I'd be suprised if the value made any difference.

File: src/tests/topp/THIRDPARTY/PercolatorAdapter_1_out.idXML (hunk 2 above)
Comment (cbielow) [reply src/tests/topp/THIRDPARTY/PercolatorAdapter_1_out.idXML:43]: that's the INI part of the story... somehow, the other twin of the duplicated parameters wins here...
But I'm not sure it also dominates when doing 'getStringOption_()' in TOPP's main_()

**Comment by timosachsenberg** [comment]
@jpfeuffer I recall that there was some overlap between flag and string options in terms of semantics. My feeling is that the string option is the preferred one (as this was also discussed in the linked PR/issue). What is your take on that?

**Comment by jpfeuffer** [comment]
Flag only exists in TOPP.
String also in DefParamHandler. If you transfer to underlying algos you need to convert anyway. Do we even have a Boolean UserParam? I think it is represented by Int or String.
Flag is always default = false

That's why I mostly use String. But I don't care how it is done in general, as long as it's not confusing.

**Comment by timosachsenberg** [comment]
I think the Boolean UserParam is represented by  String with restrictions true and false

**Comment by jpfeuffer** [comment]
We use -post_processing_tdc as a flag. So it needs to stay. Not sure what the consensus was above.

**Comment by cbielow** [comment]
> We use -post_processing_tdc as a flag in quantms. So it needs to stay like that. Not sure what the consensus was above.

This PR does not change that behaviour.
So its win-win.

Lets merge.

**Comment by cbielow** [comment]
if flags are a problem, in e.g. galaxy, then we'd need a more holistic approach for all tools anyway -- preferably on the Galaxy side of things.
