### PR TITLE
[FIX] BasicStatistics: reasonable results with vectors of zeroes

### LINKED ISSUE #5981: MapAlignerPoseClustering FATAL: uncaught exception!
This algorithm crashes from the develop-version with a specific dataset, but in TOPPAS there seems to be no problem at all (2.7.0). The error is :
```

Picking a reference (by size) ... done
Progress of 'Aligning input maps':
  20.44 %               
---------------------------------------------------
FATAL: uncaught exception!
---------------------------------------------------
last entry in the exception handler: 
exception of type InvalidValue occurred in line 1040, function virtual void OpenMS::PoseClusteringAffineSuperimposer::run(const std::vector<OpenMS::Peak2D>&, const std::vector<OpenMS::Peak2D>&, OpenMS::TransformationDescription&) of /home/eeko/data/OpenMS_build/OpenMS/src/openms/source/ANALYSIS/MAPMATCHING/PoseClusteringAffineSuperimposer.cpp
error message: the value '-nan' was used but is not valid; Superimposer could not compute an initial transformation!You can try to increase 'max_num_peaks_considered' to solve this.
---------------------------------------------------
Aborted
```

My parameters:

`MapAlignerPoseClustering -algorithm:max_num_peaks_considered -1 -algorithm:superimposer:mz_pair_max_distance 0.05 -algorithm:pairfinder:distance_MZ:max_difference 10.0 -algorithm:pairfinder:distance_MZ:unit ppm `

Exactly the same params were used in TOPPAS.

### PR DESCRIPTION
**Pull request by enetz**
`BasicStatistics` `mean_` and `variance_` returned `-nan` when given a vector of only zeroes, due to dividing by the sum.

This should fix #5981 and possibly a few other unexpected `nan` issues.

This is one possible solution, but more input would be appreciated.
Problems here are:
`sum_` and `mean_` would be zero for a vector like this as well: [-5, -3, 0, 3, 5], but the variance would not be zero.
Still we use `variance_ /= sum_` as a step in the calculation, which would cause a `nan`.

# Description

Please include a summary of the change and which issue is fixed.

# Checklist:
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.
- Or click on the action: e.g., for clang-format linting

# Note:
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

# Advanced commands (admins / reviewer only):
- `/reformat` (experimental) applies the clang-format style changes as additional commit
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds

### CODE REVIEW

File: src/openms/include/OpenMS/MATH/STATISTICS/BasicStatistics.h [hunk 1]
```diff
@@ -132,6 +132,12 @@ namespace OpenMS
           variance_ += *iter * diff;
         }
         variance_ /= sum_;
+
+        if (sum_ == 0 && (std::isnan(mean_) || std::isinf(mean_)) )
```
Comment (timosachsenberg) [inline src/openms/include/OpenMS/MATH/STATISTICS/BasicStatistics.h:136]: there are two places where this could be added in the header

Comment (timosachsenberg) [reply src/openms/include/OpenMS/MATH/STATISTICS/BasicStatistics.h:136]: why is the sum_ == 0 required?
would std::isnan(mean_) || std::isinf(mean_) be enough?

Comment (enetz) [reply src/openms/include/OpenMS/MATH/STATISTICS/BasicStatistics.h:136]: I wanted to avoid fixing stuff that shouldn't be fixed. If those numbers are `nan` because there is a `nan` in the given input, then returning a `0` would be wrong. We should make sure we only set to `0` when it's obvious the `nan` was caused by the calculations in this class.

**Comment by timosachsenberg** [comment]
rebuild jenkins
