### PR TITLE
small margin for the clustering grid

### LINKED ISSUE #2027: FeatureFinderMultiplex crash on Bruker data
`FeatureFinderMultiplex` crashes here [1] with the following exception.
```
Error: Unexpected internal error (This position (x,y)=(729.069,1.352) is outside the range of the grid. (194.911 < x < 1755.18, 1.352 < y < 8.291))
```
The first spectrum of the dataset has the retention time `1.352 sec`. During processing the `RT` position acquires a minute rounding error
```
1.352 - 2.2e-16 < 1.352
```
which leads to the exception.

[1] https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/COMPARISON/CLUSTERING/ClusteringGrid.cpp#L101

### PR DESCRIPTION
**Pull request by lars20070**
This change adds a small margin to the grid on which the filtering results are clustered.

Due to minute rounding errors, data points might fall outside the expected range of the grid. The margin prevents that. Resolves #2027.

### CODE REVIEW

**Comment by lars20070** [comment]
@jpfeuffer Can you see what the build problem is? (I have restarted a couple of times.)

**Comment by jpfeuffer** [comment]
Resolved. restarted travis

**Comment by jpfeuffer** [comment]
Do we want that to be changeable? Or can you prove that this magic constant will always prevent the aforementioned problems (e.g. what if the rounding error is bigger than this margin)?

**Comment by lars20070** [comment]
The rounding error is of order of the double precision e-16 and not related to the data. IMO, any small margin > e-16 will do.

**Comment by cbielow** [comment]
please go for 1e-15 thenm since the current 0.001 is well within high-res MS territory. Not sure if it matters in this case though.

**Comment by lars20070** [comment]
Ok. - Any deviation larger than `e-15` is not down to the `double` precision and will lead to an exception.

File: src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexClustering.cpp [hunk 1]
```diff
@@ -73,6 +73,14 @@ namespace OpenMS
     double rt_min = exp_profile.getMinRT();
     double rt_max = exp_profile.getMaxRT();
     
+    // extend the grid by a small absolute margin
+    double mz_margin = pow(10,-15);
```
Comment (cbielow) [inline src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexClustering.cpp]: why call a function?
use `1e-15`

**Comment by jpfeuffer** [comment]
If it passes, +1
