### PR TITLE
[FIX] TOPPView: fix crash when viewing certain Chromatograms

### LINKED ISSUE #7220: terminate called after throwing an instance of 'std::length_error'   what():  vector::_M_range_insert
Hello everyone,
Thanks for this awesome project!

I am a complete newbie in Chromatography and I have been trying to view the results from a .wiff / .wiff.scan file acquired from a SCIEX QTrap device.

After converting the .wiff / .wiff.scan files to .mzML  using ProteoWizard ( https://proteowizard.sourceforge.io/ ) I get the .mzML files for the experiment and try to open them using TOPPView I get a crash after clicking on one of the peptides on the lower screen

screen153

This is the console log : 

```
./TOPPView 
Icon theme "elementary" not found.
Expecting a single source file in mzML. Found 2 will take only first one for rewriting.
..
INFO: done loading all 
terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_range_insert
Aborted
```

I have tried to both use the original file .mzML and also pass it through FileConverter to maybe strip compressed symbols  using : 

```
FileConverter -in  ~/Documents/Programming/multiquant/test-High\ A1.mzML -out ~/Documents/Programming/multiquant/testA1.mzML
```

I am using the latest master commit that in the about window of TOPPView is listed as 3.1.0-pre-develop-2023-11-21

I built the project on Ubuntu 22.04.3 LTS
on the following kernel 6.2.0-37-generic #38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

Thank you for your help!

I am also uploading the two sample files that have the same behavior so you can reproduce my problem

[test.zip](https://github.com/OpenMS/OpenMS/files/13439623/test.zip)

### PR DESCRIPTION
**Pull request by cbielow**
## Description

fixes #7220

which are actually two unrelated problems:
1) when viewing a TIC chrom, its ranges were not precomputed and lead to inverse iterator ranges (+inf RT to -inf RT).
2) when creating a new 1D paint window for Chroms for the first time, there is no RT range, hence updating it does not work.

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

File: src/openms/source/KERNEL/MSExperiment.cpp [hunk 1]
```diff
@@ -299,7 +301,6 @@ namespace OpenMS
 
       // ranges
       this->extendMZ(cp.getMZ());// MZ
-      cp.updateRanges();
       this->extend(cp);// RT and intensity from chroms's range
```
Comment (timosachsenberg) [inline src/openms/source/KERNEL/MSExperiment.cpp:304]: I use this opportunity to ping https://github.com/OpenMS/OpenMS/pull/6774

**Comment by AmmarkoV** [comment]
Thank you @cbielow this resolved Issue #7220

**Comment by timosachsenberg** [comment]
thanks!

**Review by timosachsenberg — APPROVED** [review]
