### PR TITLE
[FIX] implement HashGrid.find to avoid "at" with exceptions

### LINKED ISSUE #4625: QTCluster happily working with exceptions
making it impossible to use exception breakpoints.
https://github.com/OpenMS/OpenMS/blob/d17cc251fd0c4068eb253b03c9fb107897771fdc/src/openms/source/ANALYSIS/MAPMATCHING/QTClusterFinder.cpp#L457

### PR DESCRIPTION
**Pull request by jpfeuffer**
fixes #4625

### CODE REVIEW

File: src/openms/include/OpenMS/COMPARISON/CLUSTERING/HashGrid.h [hunk 1]
```diff
@@ -405,16 +401,28 @@ namespace OpenMS
 
     /**
      * @warning Currently needed non-const by HierarchicalClustering.
-     */
-    grid_iterator grid_begin() { return cells_.begin(); }
+    */
+    typename Grid::mapped_type & grid_at(const CellIndex & x) { return cells_.at(x); }
```
Comment (timosachsenberg) [inline src/openms/include/OpenMS/COMPARISON/CLUSTERING/HashGrid.h:405]: can this be const (as well as the other grid_finds)

Comment (jpfeuffer) [reply src/openms/include/OpenMS/COMPARISON/CLUSTERING/HashGrid.h:405]: this one yes.  other grid_find, no, otherwise you cannot overload since only the return type is different.

**Comment by timosachsenberg** [comment]
looks good

File: src/openms/include/OpenMS/COMPARISON/CLUSTERING/HashGrid.h (hunk 1 above)
Comment (jpfeuffer) [reply src/openms/include/OpenMS/COMPARISON/CLUSTERING/HashGrid.h:405]: ah no, actually none of them.

Comment (jpfeuffer) [reply src/openms/include/OpenMS/COMPARISON/CLUSTERING/HashGrid.h:405]: both have colliding overloads
