### PR TITLE
Fix: Doxygen Docs contain stty warning for TOPP tool output

### LINKED ISSUE #7865: Doxygen Docs contain stty warning for TOPP tool output
Seems to be a strange stty: line in the doxygen docs in the TOPP tools. 

See this link as well: https://openms.de/current_doxygen/html/TOPP_MassTraceExtractor.html

Image

### PR DESCRIPTION
**Pull request by definitelynotchirag**
## Description

fixes #7865
This fixes the "stty: 'standard input': Inappropriate ioctl for device" error that appeared in the generated command-line documentation. The error occurred because the TOPP tools were trying to use terminal control operations when run in a non-interactive context during documentation generation.
I've added environment variables at the process level to properly handle terminal operations when generating TOPP tool documentation:

## Checklist
- [x] Make sure that you are listed in the AUTHORS file
- [x] Add relevant changes and new features to the CHANGELOG file
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes
- [x] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.seqan.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

## Summary by CodeRabbit

- **Chores**
	- Updated the project's contributor acknowledgments, adding "Chirag Dave" and adjusting the entry for "Peter Jones."
- **Bug Fixes**
	- Resolved a warning in documentation output related to the TOPP tool.
- **Refactor**
	- Streamlined environment configuration for improved consistency during process execution.

### CODE REVIEW

File: AUTHORS [hunk 1]
```diff
@@ -117,7 +117,8 @@ the authors tag in the respective file header.
  - Vipul Patel
  - Virginia Rossow
  - Volker Mosthaf
+ - Chirag Dave
```
Comment (cbielow) [inline AUTHORS]: please sort alphabetically

File: doc/doxygen/parameters/TOPPDocumenter.cpp [hunk 2]
```diff
@@ -192,8 +192,10 @@ bool generate(const ToolListType& tools, const String& prefix, const String& bin
     QProcess process;
     process.setProcessChannelMode(QProcess::MergedChannels);
     QStringList env = QProcess::systemEnvironment();
-    env << String("COLUMNS=110").toQString(); // Add an environment variable (used by each TOPP tool to determine width of help text (see TOPPBase))
-    process.setEnvironment(env);
+    qputenv("COLUMNS", "110"); // Add an environment variable (used by each TOPP tool to determine width of help text (see TOPPBase))
+    // Add Global environment variable to suppress stty errors
+    qputenv("TERM", "dumb");
+    qputenv("STTY", "/bin/true");
```
Comment (cbielow) [inline doc/doxygen/parameters/TOPPDocumenter.cpp]: this changes the ENV of the current process and that does it multiple times.
Changing the env of the child process should be sufficient?!

File: AUTHORS [hunk 3]
```diff
@@ -117,7 +117,8 @@ the authors tag in the respective file header.
...
  - Witold Wolski
  - Xiao Liang
  - Yasset Perez-Riverol
- - Peter Jones
\ No newline at end of file
+ - Peter Jones
```
Comment (cbielow) [inline AUTHORS]: remove, its a duplicate

**Review by cbielow — CHANGES_REQUESTED** [review]
Please mention 
`fixes #7865` in the description, for proper cross-linking to the issue (mentioning it in the commit message is good, but not sufficient).

See comments below

File: doc/doxygen/parameters/TOPPDocumenter.cpp (hunk 2 above)
Comment (definitelynotchirag) [reply doc/doxygen/parameters/TOPPDocumenter.cpp]: Yeah I tried Changing the env of the child process but it didn't solved the issue!
i think because for ExternalProcess there doesn't seem to be a way to access its internal QProcess object or set environment variables directly
I think the simple fix will be to set the global environments outside the for loop at the beginning of the function. I will make the necessary changes!! Thank you

File: AUTHORS [hunk 4]
```diff
@@ -120,4 +121,3 @@ the authors tag in the respective file header.
  - Witold Wolski
  - Xiao Liang
  - Yasset Perez-Riverol
- - Peter Jones
```
Comment (poshul) [inline AUTHORS:123]: Please add Peter back as an author (ideally in the correct alphabetical position)

Comment (definitelynotchirag) [reply AUTHORS:123]: Yeah!! Peter Jones do exist and its in alphabetical order. Thanks

Comment (poshul) [reply AUTHORS:123]: So he is. Good catch.

**Comment by poshul** [comment]
It looks like the connection to our cdash server timed out on the CI runs. I've just restarted them.

**Comment by poshul** [comment]
with the CDASH server having been out all day, I've just added some code to not fail CI checks. Can you sync your branch with develop, and we can see how the CI looks?

**Comment by definitelynotchirag** [comment]
@poshul done!!

File: doc/doxygen/parameters/TOPPDocumenter.cpp (hunk 2 above)
Comment (cbielow) [reply doc/doxygen/parameters/TOPPDocumenter.cpp]: upon a closer look, the whole QProcess is useless, since it does not affect the ExternalProcess down below.
Probably an oversight.
Your solution should fix that along with the stty warning.
thanks!

If you want, please remove https://github.com/OpenMS/OpenMS/blob/b2f6bc49351fe9c663b533f3ea499bfb2b4b4c3b/doc/doxygen/parameters/TOPPDocumenter.cpp#L197C1-L200C53
entirely, along with the QProcess header.

Comment (definitelynotchirag) [reply doc/doxygen/parameters/TOPPDocumenter.cpp]: Yeah! I have removed the Qprocess header completely, please check it out! Thanks

Comment (cbielow) [reply doc/doxygen/parameters/TOPPDocumenter.cpp]: looks good.
Did you commit all your changes?
Since https://github.com/OpenMS/OpenMS/pull/7868/files#diff-738d9fd1d50c311636acdd1ec1e67c2eb75b73241d8c471845e32535bee12ed3R17
is still present.

Comment (definitelynotchirag) [reply doc/doxygen/parameters/TOPPDocumenter.cpp]: Sorry mybad! I have removed the include line. Thank you!

**Review by cbielow — APPROVED** [review]
thanks for fixing this!
