### PR TITLE
fix: skip peaks that have already been found when using wide boundary…

### LINKED ISSUE #8315: penSwathWorkflow hangs when boundary_selection_method is set to widest
### Operating System and Hardware

Mac OS

### OpenMS Version

pyOpenMS 3.4

### Installation Method

Official Installer

### Bug Description

Hi,

when I set the parameter -Scoring:TransitionGroupPicker:boundary_selection_method to widest, OpenSwathWorkflow enters an endless loop and never finishes (it eventually aborts after a long time). When I use largest, everything works fine.

Is there a known reason for this behavior? Could this be a bug or related to how the peak boundaries are determined?

Best regards

### PR DESCRIPTION
**Pull request by singjc**
… selection method

## Description

Addresses #8315. Added a check in `findWidestPeakIndices` to skip peaks that have already been processed/checked. 

## Checklist
- [x] Make sure that you are listed in the AUTHORS file
- [x] Add relevant changes and new features to the CHANGELOG file
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes
- [x] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.seqan.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

## Summary by CodeRabbit

* **Bug Fixes**
  * Ignored zero-intensity peaks when computing peak widths, preventing already-consumed or negligible peaks from skewing width measurements.
  * Improved accuracy and stability of transition group peak analysis, reducing false width estimates and smoothing downstream peak selection.

### CODE REVIEW

File: src/openms/source/ANALYSIS/OPENSWATH/MRMTransitionGroupPicker.cpp [hunk 1]
```diff
@@ -127,6 +127,9 @@ namespace OpenMS
     {
       for (Size k = 0; k < picked_chroms[i].size(); ++k)
       {
+        // Skip peaks already "consumed" by previous iterations
+        if (picked_chroms[i][k].getIntensity() <= 1e-11) {continue; }
```
Comment (timosachsenberg) [inline src/openms/source/ANALYSIS/OPENSWATH/MRMTransitionGroupPicker.cpp]: Is it Zero? Note that floating point comparison against zero is fine if intensities are set to zero (and not a result of a calculation that involves rounding errors)

Comment (singjc) [reply src/openms/source/ANALYSIS/OPENSWATH/MRMTransitionGroupPicker.cpp]: Yes, when creating peak-group features (either by largest intensity or by widest peak), the assessed peaks are set to zero as a way to indicate the peak was already added/checked for a peak-group feature.

Comment (timosachsenberg) [reply src/openms/source/ANALYSIS/OPENSWATH/MRMTransitionGroupPicker.cpp]: In this case, I would test for exact 0.0.

Comment (singjc) [reply src/openms/source/ANALYSIS/OPENSWATH/MRMTransitionGroupPicker.cpp]: kk, makes sense. Changed to check for exact 0.0.

**Review by timosachsenberg — APPROVED** [review]
