### PR TITLE
force OpenGL 2.1 on macOS

### LINKED ISSUE #6215: [TOPPView] 3D view crashes in MacOS
Screen Shot 2022-07-07 at 10 15 27 AM

I tried to open an mzml file with Toppview, and this is the error message I got. 
Both "Switch to 3D view" and opening an mzML file in 3D seem to crash.

### PR DESCRIPTION
**Pull request by jpfeuffer**
fixes #6215

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

File: src/openms_gui/source/VISUAL/APPLICATIONS/GUITOOLS/TOPPView.cpp [hunk 1]
```diff
@@ -141,6 +141,17 @@ int main(int argc, const char** argv)
...
   try
   {
+#if defined(__APPLE__)
+    // see https://bugreports.qt.io/browse/QTBUG-104871
+    // if you link to QtWebEngine and the corresponding macros are enabled, it will
+    // try to default to OpenGL 4.1 on macOS (for hardware acceleration of WebGL in Chromium, which we do not need yet)
+    // but our OpenGL code for 3D View is written in OpenGL 2.x.
+    // Now we force 2.1 which is also available on all? Macs.
+    QSurfaceFormat format;
+    format.setVersion(2, 1); // the default is 2, 0
```
Comment (timosachsenberg) [inline src/openms_gui/source/VISUAL/APPLICATIONS/GUITOOLS/TOPPView.cpp:151]: why is default 2.0 but setting to 2.1 solbes the issue with the default being 4.1? confused :)

Comment (jpfeuffer) [reply src/openms_gui/source/VISUAL/APPLICATIONS/GUITOOLS/TOPPView.cpp:151]: please see the linked Qt issue and related code. Too much to explain.

Comment (jpfeuffer) [reply src/openms_gui/source/VISUAL/APPLICATIONS/GUITOOLS/TOPPView.cpp:151]: Feel free to comment on the issue to ask for more background info

Comment (timosachsenberg) [reply src/openms_gui/source/VISUAL/APPLICATIONS/GUITOOLS/TOPPView.cpp:151]: it's fine - no questions asked :P guess it just falls back to 4.1 for everything != 4.1 or 2.1

Comment (jpfeuffer) [reply src/openms_gui/source/VISUAL/APPLICATIONS/GUITOOLS/TOPPView.cpp:151]: Webengine forces 3.2+
macOS only has 2.1 and 4.1
So with Webengine on macOS it defaults to 4.1. We cannot do that, so we have to go to 2.x
Since macOS only has 2.1, we go 2.1

File: src/openms_gui/source/VISUAL/APPLICATIONS/GUITOOLS/TOPPView.cpp [hunk 2]
```diff
@@ -141,6 +141,17 @@ int main(int argc, const char** argv)
...
+    QSurfaceFormat::setDefaultFormat(format);
```
Comment (cbielow) [inline src/openms_gui/source/VISUAL/APPLICATIONS/GUITOOLS/TOPPView.cpp:152]:
```suggestion
    QSurfaceFormat::setDefaultFormat(format); // should be done before creating a QApplication
```

**Review by cbielow — APPROVED** [review]
looks good from my side.
Cannot test obviously, but since the PR only affects MacOS it can only get better I guess :)

**Review by timosachsenberg — APPROVED** [review]
