### PR TITLE
TOPPView bugfixes for 2D / 3D modes; log intensity mode for 3D view

### LINKED ISSUE #1510: log 3D view in TOPPView broken
When toggling 'log' in 3D view, the resulting view is empty.

screen shot 2015-07-10 at 12 17 48

### PR DESCRIPTION
**Pull request by hannesveit**
Should fix #1510, #2219, #2221, #2223

Check out the new log intensity mode in 3D:

screen shot 2016-10-05 at 18 12 50

Happy #hacktoberfest everyone! ;)

### CODE REVIEW

**Comment by timosachsenberg** [comment]
nice

File: src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp [hunk 1]
```diff
@@ -1581,21 +1581,6 @@ namespace OpenMS
     if (w)
     {
       intensity_button_group_->button(index)->setChecked(true);
-      Spectrum2DWidget* w2d = dynamic_cast<Spectrum2DWidget*>(w);
```
Comment (timosachsenberg) [inline src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp]: this block is not needed anymore?

Comment (hannesveit) [inline src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp]: nope, i've moved this functionality to Spectrum2DCanvas::intensityModeChange_() and also fixed the bug there that only the currently active layer changes its gradient in log-mode vs non-log mode.
