### PR TITLE
fix: RT centroid calculation

### LINKED ISSUE #7780: MassTraceDetection: rt apex calculation is of by a bit
A bug in mass trace detection leads to a small distortion in the apex RT value.
Red is correct if intensity weighting is performed.
Old code uses sum of intensities to weight but then normalized by trapezoid peak area.

image

preparing a fix...

### PR DESCRIPTION
**Pull request by timosachsenberg**
## Description

Fixes https://github.com/OpenMS/OpenMS/issues/7780

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.seqan.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

### CODE REVIEW

File: src/openms/source/KERNEL/MassTrace.cpp [hunk 1]
```diff
@@ -395,22 +397,33 @@ namespace OpenMS
...
+      double trace_area = 0;
 
       double rt_before = trace_peaks_[0].getRT();
       for (MassTrace::const_iterator l_it = trace_peaks_.begin() + 1; l_it != trace_peaks_.end(); ++l_it)
       {
-        wmean_rt += l_it->getIntensity() * l_it->getRT() * (l_it->getRT() - rt_before);
+        double rt_diff = l_it->getRT() - rt_before;                
+        wmean_rt += l_it->getIntensity() * l_it->getRT() * rt_diff;
         rt_before = l_it->getRT();
+        trace_area += l_it->getIntensity() * rt_diff;
```
Comment (timosachsenberg) [inline src/openms/source/KERNEL/MassTrace.cpp:425]: Now uses same summation method as for wmean_rt.
Before it calculated and took the mass trace area (which was trapezoid).
