### PR TITLE
[FIX] supress QT::splitbehaviour deprecated warning until 5.14

### LINKED ISSUE #5936: warning: `QString::SkipEmptyParts` is deprecated
```shell
/home/USER/Development/OpenMs/src/openms_gui/source/VISUAL/APPLICATIONS/TOPPASBase.cpp: In member function ‘void OpenMS::TOPPASBase::openFilesInTOPPView(QStringList)’:
/home/USER/Development/OpenMs/src/openms_gui/source/VISUAL/APPLICATIONS/TOPPASBase.cpp:1515:94: warning: ‘QString::SkipEmptyParts’ is deprecated [-Wdeprecated-declarations]
 1515 |         files = files.join("#SpLiT_sTrInG#+#SpLiT_sTrInG#").split("#SpLiT_sTrInG#", QString::SkipEmptyParts);
      |                                                                                              ^~~~~~~~~~~~~~
In file included from /usr/include/qt/QtCore/qobject.h:47,
                 from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/qframe.h:44,
                 from /usr/include/qt/QtWidgets/qabstractscrollarea.h:44,
                 from /usr/include/qt/QtWidgets/qmdiarea.h:44,
                 from /usr/include/qt/QtWidgets/QMdiArea:1,
                 from /home/USER/Development/OpenMs/src/openms_gui/include/OpenMS/VISUAL/EnhancedWorkspace.h:40,
                 from /home/USER/Development/OpenMs/src/openms_gui/include/OpenMS/VISUAL/APPLICATIONS/TOPPASBase.h:42,
                 from /home/USER/Development/OpenMs/src/openms_gui/source/VISUAL/APPLICATIONS/TOPPASBase.cpp:35:
/usr/include/qt/QtCore/qstring.h:605:9: note: declared here
  605 |         SkipEmptyParts Q_DECL_ENUMERATOR_DEPRECATED
      |         ^~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by Amit0617**
# Description

Please include a summary of the change and which issue is fixed.
Fixes #5936

# Checklist:
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.
- Or click on the action: e.g., for clang-format linting

# Note:
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

# Advanced commands (admins / reviewer only):
- `/rebase` will try to rebase the PR on the current develop branch.
- `/reformat` (experimental) applies the clang-format style changes as additional commit
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds

### CODE REVIEW

File: src/openms_gui/source/VISUAL/APPLICATIONS/TOPPASBase.cpp [hunk 1]
```diff
@@ -1512,7 +1512,10 @@ namespace OpenMS
       if (ret == QMessageBox::Cancel) return; // Escape was pressed
       if (ret == QMessageBox::Yes)
       {
+#pragma GCC diagnostic push
+#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
```
Comment (jpfeuffer) [inline src/openms_gui/source/VISUAL/APPLICATIONS/TOPPASBase.cpp:1516]: Can you please add a comment on which warning this is suppressing and why or when it can be removed.

**Review by jpfeuffer — CHANGES_REQUESTED** [review]

**Review by timosachsenberg — APPROVED** [review]
