### PR TITLE
Fix: OSW, pass im_range to scoreIdentification method

### LINKED ISSUE #7883: OpenSwathWorkflow: Error integrating drift time when processing non-ion mobility DIA data
OpenSwathWorkflow seems to attempt to integrate with drift time for regular DIA (non ion mobility) data. The ion mobility params are turned off, so I'm not sure why it would still try to integrate with drift_time. 

Also noticed `use_ms1_ion_mobility` seems to be a duplicated param.

### params

```
TOPPBase.cpp(1662): Value of string option 'no_progress': 0
TOPPBase.cpp(1662): Value of string option 'in': /data/input/20200902_Erli_pro_117.mzML.gz
TOPPBase.cpp(1662): Value of string option 'tr': /data/input/library.pqp
TOPPBase.cpp(1662): Value of string option 'out_features': /data/20200902_Erli_pro_117.osw
TOPPBase.cpp(1662): Value of string option 'tr_type': 
TOPPBase.cpp(1662): Value of string option 'out_features_type': 
TOPPBase.cpp(1662): Value of string option 'out_qc': 
TOPPBase.cpp(1662): Value of string option 'tr_irt': /data/input/20200902_Erli_pro_117_Q1_run_peaks_linear.pqp
TOPPBase.cpp(1662): Value of string option 'tr_irt_nonlinear': /data/input/20200902_Erli_pro_117_Q1_run_peaks.pqp
TOPPBase.cpp(1662): Value of string option 'rt_norm': 
TOPPBase.cpp(1662): Value of string option 'swath_windows_file': 
TOPPBase.cpp(1662): Value of string option 'out_chrom': /data/20200902_Erli_pro_117.sqMass
TOPPBase.cpp(1662): Value of string option 'split_file_input': 0
TOPPBase.cpp(1662): Value of string option 'use_elution_model_score': 0
TOPPBase.cpp(1662): Value of string option 'force': 1
TOPPBase.cpp(1662): Value of string option 'pasef': 0
TOPPBase.cpp(1662): Value of string option 'sort_swath_maps': 0
TOPPBase.cpp(1662): Value of string option 'enable_ms1': true
TOPPBase.cpp(1662): Value of string option 'enable_ipf': true
TOPPBase.cpp(1662): Value of int option 'batchSize': 1000
TOPPBase.cpp(1662): Value of int option 'outer_loop_threads': -1
TOPPBase.cpp(1662): Value of int option 'ms1_isotopes': 3
TOPPBase.cpp(1662): Value of int option 'debug': 1
TOPPBase.cpp(1662): Value of double option 'min_rsq': 0.95
TOPPBase.cpp(1662): Value of double option 'min_coverage': 0.6
TOPPBase.cpp(1662): Value of string option 'readOptions': cacheWorkingInMemory
TOPPBase.cpp(1662): Value of string option 'mz_correction_function': quadratic_regression_delta_ppm
TOPPBase.cpp(1662): Value of string option 'tempDirectory': /data/tmp/
TOPPBase.cpp(1662): Value of double option 'min_upper_edge_dist': 1.0
TOPPBase.cpp(1662): Value of string option 'use_ms1_ion_mobility': false
TOPPBase.cpp(1662): Value of string option 'matching_window_only': false
TOPPBase.cpp(1662): Value of double option 'mz_extraction_window': 20.0
TOPPBase.cpp(1662): Value of string option 'mz_extraction_window_unit': ppm
TOPPBase.cpp(1662): Value of double option 'rt_extraction_window': 300.0
TOPPBase.cpp(1662): Value of double option 'ion_mobility_window': -1.0
TOPPBase.cpp(1662): Value of string option 'extraction_function': tophat
TOPPBase.cpp(1662): Value of double option 'extra_rt_extraction_window': 0.0
TOPPBase.cpp(1662): Value of double option 'irt_mz_extraction_window': 40.0
TOPPBase.cpp(1662): Value of double option 'irt_im_extraction_window': -1.0
TOPPBase.cpp(1662): Value of string option 'irt_mz_extraction_window_unit': ppm
TOPPBase.cpp(1662): Value of double option 'mz_extraction_window_ms1': 20.0
TOPPBase.cpp(1662): Value of string option 'mz_extraction_window_ms1_unit': ppm
TOPPBase.cpp(1662): Value of string option 'use_ms1_ion_mobility': false
```

### Log

```
MRMTransitionGroupPicker.h(214): **** Creating MRMFeature for peak 0 in chrom. 0 with POS: 809.17 INT: 112815 and borders 805.843 817.14 (11.2979)
MRMTransitionGroupPicker.h(979):  * peak 0 left boundary 805.843 with inty 397496
MRMTransitionGroupPicker.h(980):  * peak 0 right boundary 817.14 with inty 397496
MRMTransitionGroupPicker.h(979):  * peak 1 left boundary 803.017 with inty 8280.83
MRMTransitionGroupPicker.h(980):  * peak 1 right boundary 825.609 with inty 8280.83
MRMTransitionGroupPicker.h(1008):  - Recalculating right peak boundaries 821.375 mean / best 817.14 std 4.23444 : 1 coefficient of variation
MRMTransitionGroupPicker.h(1016):  - CV too large: correcting right boundary to  825.609
MRMTransitionGroupPicker.h(1025):  - Recalculating left peak boundaries 804.43 mean / best 805.843 std 1.41281 : 1 coefficient of variation
MRMTransitionGroupPicker.h(1033):  - CV too large: correcting left boundary to  805.843
MRMTransitionGroupPicker.h(735):  ** Removed 2 peaks enclosed in and 0 peaks overlapping with added feature.
MRMTransitionGroupPicker.h(153): **** No more peaks left. Nr. chroms: 6
MRMFeatureFinderScoring.cpp(607): Scoring feature RT: 873.494 MZ: 0 INT: 1.59159e+07 == 13136 [ expected RT 9.69507 / 915.457 ] with 6 transitions and 6 chromatograms

---------------------------------------------------
FATAL: uncaught exception!
---------------------------------------------------
last entry in the exception handler: 
exception of type MissingInformation occurred in line 82, function void OpenMS::DIAHelpers::integrateWindow_(const SpectrumPtr&, double&, double&, double&, const OpenMS::RangeMZ&, const OpenMS::RangeMobility&, bool) of /code/OpenMS/src/openms/source/ANALYSIS/OPENSWATH/DIAHelper.cpp
error message: Cannot integrate with drift time if no drift time is available
---------------------------------------------------
```

### PR DESCRIPTION
**Pull request by singjc**
## Description

This addresses issue #7883 

I now pass the im_range to `scoreIdentification_` instead of recomputing it within the function, which results in an im_range with (-1,-1) if there is no drift time set in the library (i.e. non-ion mobility data).

Not sure why it was initially done that way, I'm assuming we wouldn't want to recompute it in the scoreIdentifiation method since these traces will have have the same library drift time as the detecting transitions.

## Checklist
- [x] Make sure that you are listed in the AUTHORS file
- [x] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.seqan.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

## Summary by CodeRabbit

- **New Features**
  - Introduced optional ion mobility filtering for a more refined scoring process.
- **Documentation**
  - Updated user guidance to explain the new ion mobility parameter for improved analysis control.
- **Bug Fixes**
  - Resolved issue with `im_range` handling by requiring it to be passed directly to the scoring method.

### CODE REVIEW

File: CHANGELOG [hunk 1]
```diff
@@ -27,6 +27,8 @@ OpenSwath:
 - Add auto add up spectra across the peak width in retention time for ion mobility extraction (#7742)
 - Add peak-picking for extracted ion mobilogram (#7759)
 - Add ion mobility scoring for identifying transitions for IPF (#7760)
+- - Bug fix, pass `im_range` to `scoreIdentifiction_` instead of computing it in the fucntion. Addresses issue #7883. (PR #7885)
++ - Bug fix, pass `im_range` to `scoreIdentification_` instead of computing it in the function. Addresses issue #7883. (PR #7885)
```
Comment (timosachsenberg) [inline CHANGELOG]:
```suggestion
- Bug fix, pass `im_range` to `scoreIdentification_` instead of computing it in the function. Addresses issue #7883. (PR #7885)
```

File: src/openms/include/OpenMS/ANALYSIS/OPENSWATH/MRMFeatureFinderScoring.h [hunk 2]
```diff
@@ -243,6 +243,7 @@ namespace OpenMS
      *                  the chromatograms were extracted. Use empty map if no
      *                  data is available.
      * @param drift_target The target drift value
+     * @param im_range Ion mobility subrange to consider (used as filter); can be empty (i.e. no IM filtering)
```
Comment (timosachsenberg) [inline src/openms/include/OpenMS/ANALYSIS/OPENSWATH/MRMFeatureFinderScoring.h]: Does this require some python binding updates?
Maybe this can provide more information. What happens if non IM data is scored and a user sets im_range? What if the user has IM data but the range is empty?
Should there be a default (e.g. the empty range?)

**Review by jcharkow — APPROVED** [review]
Looks good to me!

**Review by timosachsenberg — APPROVED** [review]

File: src/openms/include/OpenMS/ANALYSIS/OPENSWATH/MRMFeatureFinderScoring.h (hunk 2 above)
Comment (singjc) [reply src/openms/include/OpenMS/ANALYSIS/OPENSWATH/MRMFeatureFinderScoring.h]: No python binding updates required, this method is not wrapped.
I updated the doc to clarify that it should be empty for non-IM data.  If the use does have IM data, and it's empty, then we assume the user does not want to use the ion mobility information. The IM range is set from the library, so we assume/depend that the library was generated with IM information coordinates.
