### PR TITLE
BugFix : Fixed Targetedfileconverter crash

### LINKED ISSUE #7923: TargetedFileConverter crash
As reported in https://github.com/OpenMS/OpenMS/issues/4752#issuecomment-2734012607

Also, perhaps a minor bug in TargetedFileConverter: it crashes with an error when there are less than 8 columns in the input TSV. I was able to fix it by adding more columns (e.g. Annotation) which are listed as not being required, but it does seem like 8 columns are required, which is not what the documentation says.

### PR DESCRIPTION
**Pull request by subCode321**
## Description

fixes #7923 
## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.seqan.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

___

### **PR Type**
Bug fix

___

### **Description**
- Fixed crash in `TargetedFileConverter` when input TSV has fewer than 8 columns.

- Adjusted minimum header size requirement from 8 to 1 in `TransitionTSVFile`.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>TransitionTSVFile.cpp</strong><dd><code>Adjusted minimum header size in TransitionTSVFile</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/openms/source/ANALYSIS/OPENSWATH/TransitionTSVFile.cpp

<li>Reduced the minimum header size from 8 to 1.<br> <li> Ensured compatibility with TSV files having fewer columns.

</details>

  </td>
  <td><a href="https://github.com/OpenMS/OpenMS/pull/7924/files#diff-f3837c99c870fbfc76da765fbb4dcc50c986df9aa4be7962ed60c497734ab444">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> <details> <summary>  Need help?</summary><li>Type <code>/help how to ...</code> in the comments thread for any questions about Qodo Merge usage.</li><li>Check out the <a href="https://qodo-merge-docs.qodo.ai/usage-guide/">documentation</a> for more information.</li></details>

## Summary by CodeRabbit

- **New Features**
  - Enhanced file header processing now supports input files with minimal header content, allowing for a broader range of formats and a more flexible user experience.
  - Improved error handling provides specific feedback when required header columns are missing.

### CODE REVIEW

File: src/openms/source/ANALYSIS/OPENSWATH/TransitionTSVFile.cpp [hunk 1]
```diff
@@ -147,7 +147,7 @@ namespace OpenMS
     std::string tmp;
     std::vector<std::string> header;
     int nr_delimiters = 3;
-    Size min_header_size = 8;
+    Size min_header_size = 1;
```
Comment (cbielow) [inline src/openms/source/ANALYSIS/OPENSWATH/TransitionTSVFile.cpp]: not ideal IMHO.
If you have a header which contains commata in a column name, then comma will be preferred.
If the `min_header_size` is large, this is somewhat robust, but using `1`, this cries for errors,
Think of a more robust strategy, also look at the header, what is minimally expected. Its more than 1 column!

**Review by cbielow — CHANGES_REQUESTED** [review]
you found the correct place.
But the fix needs more thought

File: src/openms/source/ANALYSIS/OPENSWATH/TransitionTSVFile.cpp (hunk 1 above)
Comment (subCode321) [reply src/openms/source/ANALYSIS/OPENSWATH/TransitionTSVFile.cpp]: Right, I'm looking into this

Comment (subCode321) [reply src/openms/source/ANALYSIS/OPENSWATH/TransitionTSVFile.cpp]: @cbielow So I read the documentation and these are columns that are required (at minimum). So I can:

- Set the `min_header_size` to 4
- Reverse the possible delimiters order from `const char possibleDelimiters[3] = {',', ';', '\t'};` to `const char possibleDelimiters[3] = {'\t', ';', ','};` so that tabs get preference and even if headers have `,` inside their name the headers will get parsed on the basis of `tabs`.
- And since these header names are `*required` .... I can also put in a check that after parsing these 4 should be found individually

Do you think the approach looks good? Then I can make the relevant change

Header Name | Type | Description
-- | -- | --
PrecursorMz* | float | This describes the precursor ion m/z
ProductMz* | float; synonyms: FragmentMz | This specifies the product ion m/z
LibraryIntensity* | float; synonyms: RelativeFragmentIntensity | This specifies the relative intensity of the fragment ion
NormalizedRetentionTime* | float; synonyms: RetentionTime, Tr_recalibrated, iRT, RetentionTimeCalculatorScore | This specifies the expected retention time (normalized retention time)

Comment (cbielow) [reply src/openms/source/ANALYSIS/OPENSWATH/TransitionTSVFile.cpp]: yes, good strat!
Go for it.

Comment (cbielow) [reply src/openms/source/ANALYSIS/OPENSWATH/TransitionTSVFile.cpp]: if you want, also replace `const char possibleDelimiters[3]` with `const std::array<char, 3> possible_delimiters;`, which would enable easier iteration and avoid repeating '3' etc.

**Comment by subCode321** [comment]
image

image


Conversion is working!

**Comment by subCode321** [comment]
@cbielow, kindly check if the PR is good to go

File: src/openms/source/ANALYSIS/OPENSWATH/TransitionTSVFile.cpp [hunk 2]
```diff
@@ -169,10 +168,27 @@ namespace OpenMS
...
+      if (!valid_header) {
+        valid_headers = false;
+      }
     }
+
+    if (!valid_headers) {
+      throw Exception::IllegalArgument(__FILE__, __LINE__, OPENMS_PRETTY_FUNCTION,
+        "The provided TSV/CSV file is missing one or more required header columns. Please ensure it includes: PrecursorMz, ProductMz (or FragmentMz), LibraryIntensity (or RelativeFragmentIntensity), and NormalizedRetentionTime (or its synonyms).");
+    }
+
```
Comment (cbielow) [inline src/openms/source/ANALYSIS/OPENSWATH/TransitionTSVFile.cpp]: looking at the code, this is not needed after all, since this is checked here https://github.com/OpenMS/OpenMS/blob/33450e0256a122a5f79820605c969a41ed3c9bc6/src/openms/source/ANALYSIS/OPENSWATH/TransitionTSVFile.cpp#L285
for the four required headers.

File: src/openms/source/ANALYSIS/OPENSWATH/TransitionTSVFile.cpp [hunk 3]
```diff
@@ -146,15 +146,14 @@ namespace OpenMS
...
+    Size min_header_size = 4;
+    const std::array<char, 3> possible_delimiters = {'\t', ';', ','};
 
-    for (int i = 0; i < nr_delimiters; i++)
+    for (auto possible_delimiter : possible_delimiters)
     {
       header.clear();
       std::stringstream lineStream(line);
-      delimiter = possibleDelimiters[i];
+      delimiter = possible_delimiter;
```
Comment (cbielow) [inline src/openms/source/ANALYSIS/OPENSWATH/TransitionTSVFile.cpp:156]: yes, good!

**Review by cbielow — CHANGES_REQUESTED** [review]
good to go,
Please remove the second part of the new code which deals with headers (its duplicating functionality already present)

File: src/openms/source/ANALYSIS/OPENSWATH/TransitionTSVFile.cpp (hunk 2 above)
Comment (himanish-star) [reply src/openms/source/ANALYSIS/OPENSWATH/TransitionTSVFile.cpp]: I've dropped this code

Comment (subCode321) [reply src/openms/source/ANALYSIS/OPENSWATH/TransitionTSVFile.cpp]: I've dropped this additional check

**Comment by subCode321** [comment]
> good to go, Please remove the second part of the new code which deals with headers (its duplicating functionality already present)

I've removed, thanks for the review

**Review by cbielow — APPROVED** [review]

**Comment by subCode321** [comment]
@cbielow can you re-run the checks for this PR, they got stopped after the merge of branch `develop` into my branch
