### PR TITLE
minor fixes to PeptideIndexer

### LINKED ISSUE #2594: PeptideIndexer: "unknown AA" error due to selenocysteine
Since #2545, PeptideIndexer may write error messages like this:
> Error while parsing sequence MKKVV...: found an unknown AA without an estimated mass. Please use PEPTIX[123] syntax to indicate an unknown amino acid with a known mass.

While getting this information now is probably a step forward, there are some problems:
- The consequences of the error are unclear, since the tool finishes normally. Are the affected sequences ignored? Is it just a warning?
- The protein sequence that is written may be very long, in which case it isn't easy to see where the problematic character is.
- The sequence that is written may not occur exactly like that in the FASTA file: If "IL_equivalent" is set, "L" will be replaced by "I"; "invalid" letters (e.g. "U") are replaced by "X". (So if I search for "X" in the FASTA file, I may not find anything.)
- In my case, the problematic letter in the original sequence was a "U", which stands for selenocysteine and is actually correct  for the protein in question (E. coli formate dehydrogenase). The fact that OpenMS (or just PeptideIndexer?) doesn't support this points to a more general problem.

### PR DESCRIPTION
**Pull request by cbielow**
[FIX] fix PeptideIndexer crash (division by 0) if 0 peptides are mapped to the protein DB.

[FEATURE] parse protein sequences which contain modifications as AASequence (since otherwise hits in regions with modfied AA would not be found) and emit a warning to user to fix his Protein Database (fixes #2594)

### CODE REVIEW

File: src/openms/include/OpenMS/ANALYSIS/ID/PeptideIndexing.h [hunk 1]
```diff
@@ -328,6 +329,14 @@ namespace OpenMS
               String prot = proteins.chunkAt(i).sequence;
 
               prot.remove('*');
+
+              // check for invalid sequences with modifications
+              if (prot.has('[') || prot.has('('))
+              { 
+                 invalid_protein_sequence = true; // not omp-critical because its write-only
+                 prot = AASequence::fromString(prot).toUnmodifiedString();
```
Comment (timosachsenberg) [inline src/openms/include/OpenMS/ANALYSIS/ID/PeptideIndexing.h]: I think this is not thread-safe (and can't easily be fixed (without huge performance penalties) because ResidueDB is not thread-safe).
I am pretty sure that this might lead to a concurrent read/write to ResidueDB.

Comment (timosachsenberg) [reply src/openms/include/OpenMS/ANALYSIS/ID/PeptideIndexing.h]: see https://github.com/OpenMS/OpenMS/issues/905

Comment (timosachsenberg) [reply src/openms/include/OpenMS/ANALYSIS/ID/PeptideIndexing.h]: please correct me if I am wrong

Comment (cbielow) [reply src/openms/include/OpenMS/ANALYSIS/ID/PeptideIndexing.h]: you're right. So I'm going to elevate to error for now until we have a solution for ResidueDB.

**Comment by cbielow** [comment]
ready to merge
