### PR TITLE
[FIX] fix #2328 by handling unit attributes in mzid with a little slack

### LINKED ISSUE #2328: Depending on ms-gf+ version used the produced, RT might be read incorrectly
Some mzid may miss units for the retention time (solved in ms-gf+ and OpenMS for files missing units entirely), some miss parts of the unit annotation(pending).

The result of an incorrect retention time consumption usually manifests in unusually low numbers of ids mapped to features and can be easily checked with FileInfo

See here for details and my quick-fix:
https://github.com/sangtaekim/msgfplus/issues/7

### PR DESCRIPTION
**Pull request by mwalzer**
might be a fix for #2328  and extended #2134 with the drawback, that further processing might turn sour when some exotic ontology is used as unit reference, which I'd deem unlikely, but still, possible.

### CODE REVIEW

File: src/openms/source/FORMAT/HANDLERS/MzIdentMLDOMHandler.cpp [hunk 1]
```diff
@@ -490,11 +490,14 @@ namespace OpenMS
         String unitCvRef = XMLString::transcode(param->getAttribute(XMLString::transcode("unitCvRef")));
 
         CVTerm::Unit u; // TODO @mths : make DataValue usage safe!
-        if (!unitAcc.empty() && !unitCvRef.empty() && !unitName.empty())
+        if (!unitAcc.empty() && !unitName.empty())
         {
           u = CVTerm::Unit(unitAcc, unitCvRef, unitName);
+          if (unitCvRef.empty())
+          {
+            LOG_WARN << "MZID retention times with units but without unit cv reference encountered!" << endl;
```
Comment (timosachsenberg) [inline src/openms/source/FORMAT/HANDLERS/MzIdentMLDOMHandler.cpp]: this warning will also be triggered for non retention times stuff

Comment (timosachsenberg) [inline src/openms/source/FORMAT/HANDLERS/MzIdentMLDOMHandler.cpp]: I think in this case warn and consume while reporting the issue to the mzID producer is the right way to go.

**Comment by timosachsenberg** [comment]
*bump*

**Comment by timosachsenberg** [comment]
+1
