### PR TITLE
Fix/linear transform

### LINKED ISSUE #5978: FeatureLinkerUnlabeledKD produces empty consensus
I have two datasets that were run using the same method. The Map aligner works fine, all the preprocessing steps are great, but at the re-quantification step (FFmetaboIdent), even though each featureXML file generated is not empty, FeatureLinkerUnlabeledKD produces an empty consensus file. Why? When can this happen?

### PR DESCRIPTION
**Pull request by enetz**
# Description

Least-squares fitting with `Wm5::HeightLineFit2` can fail with two points that are too close to each other.
Added code to handle this specific case manually, since there is an exact solution with two points.

Fixes #5978

# Checklist:
- [x] Make sure that you are listed in the AUTHORS file
- [x] Add relevant changes and new features to the CHANGELOG file
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes
- [x] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.
- Or click on the action: e.g., for clang-format linting

# Note:
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

# Advanced commands (admins / reviewer only):
- `/reformat` (experimental) applies the clang-format style changes as additional commit
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds

### CODE REVIEW

File: src/openms/source/ANALYSIS/MAPMATCHING/TransformationModelLinear.cpp [hunk 1]
```diff
@@ -84,9 +84,22 @@ namespace OpenMS
         {
           points.push_back(Wm5::Vector2d(data_weighted[i].first, data_weighted[i].second));
         }
-        if (!Wm5::HeightLineFit2<double>(static_cast<int>(size), &points.front(), slope_, intercept_))
+        if (size == 2)
+        {
+          if (!Wm5::HeightLineFit2<double>(static_cast<int>(size), &points.front(), slope_, intercept_))
```
Comment (cbielow) [inline src/openms/source/ANALYSIS/MAPMATCHING/TransformationModelLinear.cpp:89]: why try fitting in the first place? Wouldn't computing the exact solution be enough?

Comment (enetz) [reply src/openms/source/ANALYSIS/MAPMATCHING/TransformationModelLinear.cpp:89]: yes, you are right. I will do the exact calculation directly and add another exception in case the slope or intercept are nan or inf

**Review by timosachsenberg — APPROVED** [review]
looks good... not sure though if the quotient could get super large and is useful ;)

**Comment by enetz** [comment]
failing pyOpenMS test is unrelated
