### PR TITLE
[FIX] fixing specificity of modifications in SearchParameter reading …

### LINKED ISSUE #2404: Reading of modifications in mzIdentML: terminal specificity lost
Terminal specificity of modifications in the search parameters is not read correctly from mzIdentML. This causes the loss of the specificity information and possibly problems in dealing with the resulting data.
This happens in IDFileConverter and in MSGFPlusAdapter.
Common modifications that are affected include: Acetyl (N-term), Gln->pyro-Glu (N-term Q), Glu->pyro-Glu (N-term E)

For example, "Acetyl (N-term)" in the search parameters would be represented in mzIdentML as such:
```
                        <SearchModification fixedMod="false" massDelta="42.010565" residues=".">
                                <SpecificityRules>
                                        <cvParam accession="MS:1001189" cvRef="PSI-MS" name="modification specificity peptide N-term"/>
                                </SpecificityRules>
                                <cvParam accession="UNIMOD:1" cvRef="PSI-MS" name="Acetyl"/>
                        </SearchModification>
```

However, after conversion to idXML, the terminal specificity is lost:
`<VariableModification name="Acetyl" />`

In the case of the pyro-Glu conversions, this results in invalid modifications ("Gln->pyro-Glu (Q)", "Glu->pyro-Glu (E)"), which cause e.g. a reconversion from idXML to mzIdentML to fail with the following error:
`Error: Unexpected internal error (the element 'Gln->pyro-Glu (Q)' could not be found)`

### PR DESCRIPTION
**Pull request by mwalzer**
should fix #2404

### CODE REVIEW

File: src/tests/class_tests/openms/source/MzIdentMLFile_test.cpp [hunk 1]
```diff
@@ -327,8 +339,8 @@ START_SECTION(([EXTRA] regression test for file loading on example files))
   std::vector<PeptideIdentification> peptide_ids;
   String input_path = OPENMS_GET_TEST_DATA_PATH("MzIdentMLFile_whole.mzid");
   MzIdentMLFile().load(input_path, protein_ids, peptide_ids);
-  input_path = OPENMS_GET_TEST_DATA_PATH("Mascot_MSMS_example.mzid");
-  MzIdentMLFile().load(input_path, protein_ids, peptide_ids);
+//  input_path = OPENMS_GET_TEST_DATA_PATH("Mascot_MSMS_example.mzid");
```
Comment (jpfeuffer) [inline src/tests/class_tests/openms/source/MzIdentMLFile_test.cpp]: Why did you comment out this test?

**Comment by jpfeuffer** [comment]
Otherwise looks good.

File: src/tests/class_tests/openms/source/MzIdentMLFile_test.cpp (hunk 1 above)
Comment (mwalzer) [inline src/tests/class_tests/openms/source/MzIdentMLFile_test.cpp]: Because it uses an old example mzid file from the Mascot guys... and it has some flaws. And that is why I greyed it out and did not delete it, because we can use it for flawed input testing
