### PR TITLE
Overhaul of XTandemAdapter

### LINKED ISSUE #2405: XTandemAdapter crash on "Deamidated (N)" modification
XTandemAdapter crashed, after completion of the X! Tandem search, with the following error messages:

```
Error: Unexpected internal error (The value 'Deamidated (N)' was used but is not valid! Retrieving the modification failed. It is not available for the residue 'S' and term specificity 0.)
XTandem config file: Duplicate modification assignment to origin '['. X!Tandem will ignore the first modification '42.0106'!
<XTandem config file: Duplicate modification assignment to origin '['. X!Tandem will ignore the first modification '42.0106'!> occurred 2 times
```

The following modifications were used in the search:
- fixed: Carbamidomethyl (C)
- variable: Oxidation (M), Deamidated (N), Deamidated (Q), Gln->pyro-Glu (N-term Q), Glu->pyro-Glu (N-term E), Acetyl (N-term)

Looking at the output file produced directly by X! Tandem ("_tandem_output_file.[...].t.xml"), something seems to be seriously wrong with some of the modifications:
`<aa type="M" at="6" modified="-18.01056" />` appears for many different amino acids and positions, but the mass shift only matches "Glu->pyro-Glu (N-term E)"!
Interestingly, only the "-18.01056" modification seems to be obviously misassigned. I couldn't find any instance of the case that the error message complains about, i.e. "Deamidated (N)" (mass shift 0.98402) being assigned to an "S".

### PR DESCRIPTION
**Pull request by hendrikweisser**
Simplified implementation and interface of XTandemAdapter (and underlying classes). Removed parameters that were deprecated or not useful (e.g. "refine", since most refinement parameters were not exposed in the adapter). Changed handling of default configuration file - moved essential settings to the code, removed reading by OpenMS (just pass it to X! Tandem).

Added convenience functions for creating/deleting temporary directories (with awareness of debug level) to TOPPBase; now used by MSGFPlusAdapter and XTandemAdapter.

Added function for looking up modifications by mass (shift) to ModificationDefinitionsSet. Now used to parse X! Tandem results, but might be very useful e.g. for pepXML as well.

Fixed #2405 and #2416.

X! Tandem functionality tested with versions "Vengeance" and "ALANINE".

### CODE REVIEW

**Comment by hendrikweisser** [comment]
@jpfeuffer: I would like to use this updated XTandemAdapter in my KNIME workflow. Are KNIME nightlies with the updated node automatically generated (shortly) after this gets merged? (Note that the parameters of XTandemAdapter changed.)

**Comment by jpfeuffer** [comment]
Well, the nightlies start at 9pm and end somewhere around midnight.
But I just saw that they are crashing see #2429

**Comment by hendrikweisser** [comment]
> Well, the nightlies start at 9pm and end somewhere around midnight.

Okay, so the changes in the interface won't require any extra action, then?

**Comment by hendrikweisser** [comment]
The only failing CI test at this point is the Clang time-out.

**Comment by jpfeuffer** [comment]
You might get warnings or errors when opening the old workflow with the new plugin, but I think after resetting the node and resaving it should be fine. The handling of your optional output should be fine.
I was also wondering about Travis. The failing nightlies seem to be a Mac specific problem.

**Comment by jpfeuffer** [comment]
Maybe @cbielow can comment on the use of the default file. Was it you that added this option a while ago. I remember the adapter not working correctly when that file was not available. Did you address this here?

**Comment by hendrikweisser** [comment]
> Was it you that added this option a while ago.

No, this is the first time I'm using X! Tandem.

> I remember the adapter not working correctly when that file was not available. Did you address this here?

Yes, that problem should be solved. The default in the adapter is now to *not* use a default config file. It may be that some default settings were changed in X! Tandem itself, which meant that *no* output would be written by default, unless certain settings were made (in particular, "output, proteins"). Those used to be only in the default config file, but are now in XTandemInfile, so they're always used.

**Comment by hroest** [comment]
@jpfeuffer @hendrikweisser regarding "time-out" of nodes, I think it makes sense to just restart the job before merging. It should be a good habit to only merge things that are "green" on the tests, as a general policy. Of course if clang fails too often we will have to rethink that approach.

File: src/openms/include/OpenMS/CHEMISTRY/ModificationDefinitionsSet.h [hunk 1]
```diff
@@ -133,22 +133,37 @@ namespace OpenMS
...
+       @param residue Query residue
+       @param term_spec Query term specificity
+       @param consider_variable Consider the variable modifications?
+       @param consider_fixed Consider the fixed modifications?
+       @param is_delta Is @p mass a delta mass (mass difference)?
+       @param tolerance Numeric tolerance for mass matching
+
+       @throw Exception::IllegalArgument if both @p consider_variable and @p consider_fixed are false
+    */
+    void findMatches(std::multimap<double, ModificationDefinition>& matches, double mass, const String& residue = "", ResidueModification::TermSpecificity term_spec = ResidueModification::NUMBER_OF_TERM_SPECIFICITY, bool consider_fixed = true, bool consider_variable = true, bool is_delta = true, double tolerance = 0.01) const;
```
Comment (hroest) [inline src/openms/include/OpenMS/CHEMISTRY/ModificationDefinitionsSet.h]: PS: any chance of using something more python friendly than a `multimap` ?

Comment (hendrikweisser) [inline src/openms/include/OpenMS/CHEMISTRY/ModificationDefinitionsSet.h]: Hm, `multimap` is the obvious choice here, but an alternative would be `set<pair<double, ModificationDefinition> >`. Would that help?

Is there a good reason why Cython doesn't support `multimap`?

**Comment by hendrikweisser** [comment]
Any comments from @cbielow or @lars20070?

**Comment by lars20070** [comment]
@hendrikweisser Let me test the adapter on some Bruker and Thermo data.

I downloaded `ALANINE` for `macOS`. But where is the executable?
```
/Users/lars/Downloads/tandem-osx-17-01-01-2/bin
rz-10-126-3-163:bin lars$ ls
default_input.xml	input.xml		tandem-style.css	taxonomy.xml
fasta_pro		tandem-input-style.xsl	tandem-style.xsl	test_spectra.mgf
```
Did you test `ALANINE` under `macOS`?

**Comment by lars20070** [comment]
FYI, @hendrikweisser. Reply from Ron Beavies, i.e. they ship an empty `macOS` release.
```
Unfortunately, the group that used to do the OSX compiling can't do it any more.
We are looking for someone to take their place.

Ron Beavis 
```

**Comment by hendrikweisser** [comment]
@lars20070: Thanks for the information. I tested X! Tandem only on Linux.

File: src/openms/include/OpenMS/CHEMISTRY/ModificationDefinitionsSet.h (hunk 1 above)
Comment (hroest) [inline src/openms/include/OpenMS/CHEMISTRY/ModificationDefinitionsSet.h]: No good reason. The reason is that basically nobody has done it ...

Comment (hendrikweisser) [inline src/openms/include/OpenMS/CHEMISTRY/ModificationDefinitionsSet.h]: So do you want me to change it to `set<...>`? I guess the alternatives would be to add `multimap` support to autowrap or to write some explicit Cython code.

**Comment by hendrikweisser** [comment]
Clang timed out twice after the last changes. I already restarted it once. Shall I restart it again?

File: src/openms/include/OpenMS/CHEMISTRY/ModificationDefinitionsSet.h (hunk 1 above)
Comment (hroest) [inline src/openms/include/OpenMS/CHEMISTRY/ModificationDefinitionsSet.h]: yes, that would be the ultimate solution but it takes quite a bit of effort...

**Comment by hroest** [comment]
@hendrikweisser regarding the OSX issue, would your adapter work with the latest compiled binary for OSX?

**Comment by hroest** [comment]
otherwise :+1: for a merge!

**Comment by hendrikweisser** [comment]
I've now tried it on OS X with X! Tandem Vengeance (from 2015) and the tests run through.

However, I've found a bug with the modification handling on a larger file, which I'll have to figure out before we can merge this.

**Comment by hendrikweisser** [comment]
> However, I've found a bug with the modification handling on a larger file, which I'll have to figure out before we can merge this.

Argh. The problem is caused by carriage return characters (`^M`) in some peptide sequences. X! Tandem includes those characters in the sequence, but OpenMS skips them, leading to different peptide lengths and potential "index out of range" errors in `AASequence::setModification`.

**Comment by hendrikweisser** [comment]
> Argh. The problem is caused by carriage return characters (^M) in some peptide sequences. X! Tandem includes those characters in the sequence, but OpenMS skips them, leading to different peptide lengths and potential "index out of range" errors in AASequence::setModification.

My solution was to reject such inputs, because otherwise it gets really difficult to assign modifications to the correct residues. You would now get an error message like this when trying to read in a problematic X! Tandem result file:
`Error: Unable to read file (Cannot convert string to amino acid sequence: unexpected character ' ' in: LLA ALA V GSAQ)`

**Comment by hroest** [comment]
@hendrikweisser so why are there CR in the data, do you know why they get there? Are they already there in the input fasta? Are they in the middle of the sequence?

but I agree, being strict is better than reporting the wrong data

**Comment by hendrikweisser** [comment]
> so why are there CR in the data, do you know why they get there? Are they already there in the input fasta? Are they in the middle of the sequence?

The CR come from the FASTA file. They appear in decoy sequences, so I assume it's a problem with "mimic", the program we used to create (shuffled) decoys.

**Comment by hendrikweisser** [comment]
Problems are fixed and all the checks are green again. I would merge this. Quick question though: GitHub gives me multiple merge options - "Merge pull request", "Squash and merge" or "Rebase and merge". I don't want to squash, but should I do the rebase?

**Comment by hroest** [comment]
@hendrikweisser I am generally in favor of merge as with a rebase we would have different sha1-hashes and the whole conversation above would relate to hashes that dont exist any more. I think for "small" changes without much discussion we could do rebase but for more complex PR with some discussion I would not be in favor. Maybe others can also comment

Apart from that :+1: for merge -- what will happen to the nightlies, do we want to install the new XTandem there as well?

**Comment by timosachsenberg** [comment]
+1 for merge. Rebase should only be used before opening a PR.
We will update nightlies as well but probably not this week. @cbielow any comments on this PR regarding the default file?

File: src/openms/include/OpenMS/APPLICATIONS/TOPPBase.h [hunk 2]
```diff
@@ -778,6 +778,18 @@ namespace OpenMS
...
 
+    ///@name Temporary directories
+    //@{
+    /// Creates a unique temporary directory and returns its name
+    String makeTempDirectory_() const;
+
+    /**
+       @brief Removes a (temporary) directory
+
+       If 'keep_debug' is set to a positive value (> 0), the directory is kept if the current debug level (@p debug_level_) is at least at that value.
```
Comment (cbielow) [inline src/openms/include/OpenMS/APPLICATIONS/TOPPBase.h]: `@p keep_debug`?

File: src/openms/include/OpenMS/CHEMISTRY/ModificationDefinitionsSet.h [hunk 3]
```diff
@@ -133,22 +133,37 @@ namespace OpenMS
...
+       @brief Finds modifications in the set that match a given (delta) mass
+
+       @param matches Matching modifications (output), sorted by mass error
+       @param mass Query mass
+       @param residue Query residue
+       @param term_spec Query term specificity
+       @param consider_variable Consider the variable modifications?
+       @param consider_fixed Consider the fixed modifications?
+       @param is_delta Is @p mass a delta mass (mass difference)?
+       @param tolerance Numeric tolerance for mass matching
```
Comment (cbielow) [inline src/openms/include/OpenMS/CHEMISTRY/ModificationDefinitionsSet.h]: tolerance in Da?

File: src/openms/source/ANALYSIS/DENOVO/CompNovoIdentificationBase.cpp [hunk 4]
```diff
@@ -667,11 +667,11 @@ for (set<Size>::const_iterator it = used_pos.begin(); it != used_pos.end(); ++it
 
     for (set<ModificationDefinition>::const_iterator it = fixed_mods.begin(); it != fixed_mods.end(); ++it)
     {
-      ResidueModification mod = ModificationsDB::getInstance()->getModification(it->getModification());
+      ResidueModification mod = it->getModification();
       char aa = ' ';
       if (mod.getOrigin().size() != 1 || mod.getOrigin() == "X")
       {
-        cerr << "Warning: cannot handle modification " << it->getModification() << ", because aa is ambiguous (" << mod.getOrigin() << "), ignoring modification!" << endl;
+        cerr << "Warning: cannot handle modification " << mod.getName() << ", because aa is ambiguous (" << mod.getOrigin() << "), ignoring modification!" << endl;
```
Comment (cbielow) [inline src/openms/source/ANALYSIS/DENOVO/CompNovoIdentificationBase.cpp]: would globally replacing `cerr` with `LOG_WARN` make sense here?
This would allow attaching fancy streams in the background.

File: src/openms/include/OpenMS/APPLICATIONS/TOPPBase.h (hunk 2 above)
Comment (hendrikweisser) [inline src/openms/include/OpenMS/APPLICATIONS/TOPPBase.h]: Changed.

File: src/openms/include/OpenMS/CHEMISTRY/ModificationDefinitionsSet.h (hunk 3 above)
Comment (hendrikweisser) [inline src/openms/include/OpenMS/CHEMISTRY/ModificationDefinitionsSet.h]: Added.

File: src/openms/source/ANALYSIS/DENOVO/CompNovoIdentificationBase.cpp (hunk 4 above)
Comment (hendrikweisser) [inline src/openms/source/ANALYSIS/DENOVO/CompNovoIdentificationBase.cpp]: Probably, but the class uses `cerr` throughout. I left it at that for now.

**Comment by hendrikweisser** [comment]
Thanks for the feedback, everyone! I've made the documentation changes suggested by Chris. Will merge now.

**Comment by hendrikweisser** [comment]
Regarding X! Tandem version: I'd be in favour of updating it (see #2406), but there's no immediate pressure as the older version should still work with the changes in this PR.
