### PR TITLE
[Fix] qsort() is deprecated

### LINKED ISSUE #5935: warning: `qSort()` is deprecated
```shell
/home/USER/Development/OpenMs/src/openms_gui/source/VISUAL/APPLICATIONS/TOPPASBase.cpp:488:10: warning: ‘void qSort(Container&) [with Container = QStringList]’ is deprecated: Use std::sort [-Wdeprecated-declarations]
  488 |     qSort(category_list);
      |     ~~~~~^~~~~~~~~~~~~~~
In file included from /usr/include/qt/QtCore/qlist.h:43,
                 from /usr/include/qt/QtCore/qobject.h:49,
                 from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/qframe.h:44,
                 from /usr/include/qt/QtWidgets/qabstractscrollarea.h:44,
                 from /usr/include/qt/QtWidgets/qmdiarea.h:44,
                 from /usr/include/qt/QtWidgets/QMdiArea:1,
                 from /home/USER/Development/OpenMs/src/openms_gui/include/OpenMS/VISUAL/EnhancedWorkspace.h:40,
                 from /home/USER/Development/OpenMs/src/openms_gui/include/OpenMS/VISUAL/APPLICATIONS/TOPPASBase.h:42,
                 from /home/USER/Development/OpenMs/src/openms_gui/source/VISUAL/APPLICATIONS/TOPPASBase.cpp:35:
/usr/include/qt/QtCore/qalgorithms.h:188:46: note: declared here
  188 | QT_DEPRECATED_X("Use std::sort") inline void qSort(Container &c)
      |                                              ^~~~~
```

### PR DESCRIPTION
**Pull request by Amit0617**
# Description

Please include a summary of the change and which issue is fixed.
Fixes #5935 

# Checklist:
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.
- Or click on the action: e.g., for clang-format linting

# Note:
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

# Advanced commands (admins / reviewer only):
- `/rebase` will try to rebase the PR on the current develop branch.
- `/reformat` (experimental) applies the clang-format style changes as additional commit
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds

### CODE REVIEW

File: src/openms_gui/source/VISUAL/APPLICATIONS/TOPPASBase.cpp [hunk 1]
```diff
@@ -485,7 +485,7 @@ namespace OpenMS
       category_set << String(it->second.category).toQString();
     }
     QStringList category_list = category_set.toList();
-    qSort(category_list);
+    std::sort(category_list.begin(), category_list.end(), std::less<QString>());
```
Comment (timosachsenberg) [inline src/openms_gui/source/VISUAL/APPLICATIONS/TOPPASBase.cpp:488]: Hi, would
```suggestion
    std::sort(category_list.begin(), category_list.end());
```
also work? I think QString defines an operator<
