### PR TITLE
Research OpenMS issue 8475

### LINKED ISSUE #8475: Inconsistencies with online doxygen documentation and local installation
### Operating System and Hardware

Ubuntu

### OpenMS Version

Development version

### Installation Method

Other

### Bug Description

Recently the `apply_im_peak_picking` parameter was added to OpenSWATH workflow. 

From the online doxygen documentation (version 3.5 development) I was under the assumption that the parameter took a string attached to it like `-Scoring:apply_im_peak_picking true` however it turns out that this is just a flag parameter.

Image

It seems to be correctly specified as a flag in the CLI 

Image

In the CTD it also seems to be of type bool
```
        <ITEM name="strict" value="true" type="string" description="Whether to error (true) or skip (false) if a transition in a transition group does not have a corresponding chromatogram." required="false" adv
anced="true" restrictions="true,false" />
        <ITEM name="use_ms1_ion_mobility" value="true" type="string" description="Performs ion mobility extraction in MS1. Set to false if MS1 spectra do not contain ion mobility" required="false" advanced="true
" />
        <ITEM name="apply_im_peak_picking" value="false" type="bool" description="Perform peak picking on the extracted ion mobilograms. This is useful for reducing intefering signals from co-eluting analytes in the ion mobility dimension. The peak picking will take the highest peak and discard the remaining peaks for ion mobility scoring. " required="false" advanced="true" />
```

### PR DESCRIPTION
**Pull request by timosachsenberg**
This pull request improves the documentation handling of command-line flag parameters by making them easier to distinguish from boolean options that require a value. The changes address an issue where flags and boolean parameters were not clearly differentiated in the generated documentation.

Enhancements to parameter documentation:

* In `DefaultParamHandlerDocumenter.cpp`, updated the logic to recognize boolean parameters with valid strings "true" and "false" and a default value of "false" as flag parameters, labeling them as "(flag)" in restrictions. This helps users understand that these parameters act as flags on the CLI and do not require a value.
* In `TOPPDocumenter.cpp`, added detection for flag parameters that are loaded as string values with "true"/"false" but have no valid strings, marking them as "(flag)" in the restrictions. This further clarifies the distinction between flags and value-requiring options in the HTML documentation.## Description

## Checklist
- [ ] Make sure that you are listed in the AUTHORS file
- [ ] Add relevant changes and new features to the CHANGELOG file
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes
- [ ] Updated or added python bindings for changed or new classes (Tick if no updates were necessary.)

### How can I get additional information on failed tests during CI
<details>
  <summary>Click to expand</summary>
If your PR is failing you can check out

- The details of the action statuses at the end of the PR or the "Checks" tab.
- http://cdash.seqan.de/index.php?project=OpenMS and look for your PR. Use the "Show filters" capability on the top right to search for your PR number.
  If you click in the column that lists the failed tests you will get detailed error messages.

</details>

### Advanced commands (admins / reviewer only)
<details>
  <summary>Click to expand</summary>
  
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to push.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds
  
</details>

---
:warning: Note: Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

## Summary by CodeRabbit

* **Documentation**
  * Parameter docs now show "(flag)" for boolean flag parameters instead of listing "true/false", clarifying when no CLI value is required.
  * Minor comment/formatting tidy in the documentation generator to clean up trailing whitespace.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Not sure if Params really understand flags.. I dont think so

**Review by jpfeuffer — APPROVED** [review]

File: doc/doxygen/parameters/TOPPDocumenter.cpp [hunk 1]
```diff
@@ -158,11 +158,21 @@ void convertINI2HTML(const Param& p, ostream& os)
...
+      else if (value_type == ParamValue::STRING_VALUE)
+      {
+        // Issue #8475: Flag parameters are written as type="bool" in INI, which loads
+        // as STRING_VALUE with no valid_strings. Detect these by checking if value is boolean.
+        String val = it->value.toString();
+        if (val == "true" || val == "false")
+        {
+          restrictions = "(flag)";
+        }
+      }
```
Comment (timosachsenberg) [inline doc/doxygen/parameters/TOPPDocumenter.cpp:175]: @jpfeuffer maybe just like this?

Comment (jpfeuffer) [reply doc/doxygen/parameters/TOPPDocumenter.cpp:175]: Yeah.. maybe a different styling would be cooler but I dont care much.

Comment (cbielow) [reply doc/doxygen/parameters/TOPPDocumenter.cpp:175]: not sure this works. There have been instances where people registered a string option with true/false as allowed values. If you use them as a flag, the parser will complain (I think).

Comment (cbielow) [reply doc/doxygen/parameters/TOPPDocumenter.cpp:175]: maybe we should not allow to create a string with explicit true/false restrictions. Then a flag could uniquely be identified.

Comment (timosachsenberg) [reply doc/doxygen/parameters/TOPPDocumenter.cpp:175]: Yes I think we do that. Because sometimes we need a bool that is true by default. This can't be a flag.
Apparently, a flag just loads as true or false from the ini without restrictions.
An bool that is true by default has these restrictions.
I find these semantics far from intuitive but seems we thought it is a good idea at some point ;)

Should we and how should we change this to not mess up any external stuff (maybe KNIME, Galaxy generators)?

Comment (cbielow) [reply doc/doxygen/parameters/TOPPDocumenter.cpp:175]: Option 1) invert the flag's semantics (and name), i.e. its false by default and then forbid true/false for strings
Option 2) forbid true/false for strings and use something else, e.g. `on/off`
Option 3) is not really an option: add a custom tag when registering these true-default string flags and treat them specially when writing the docs. But that's not only hacky but also brittle, if new flags are introduced and the tag is forgotten etc...

External stuff will break in any case (Option 1 and 2).

Comment (timosachsenberg) [reply doc/doxygen/parameters/TOPPDocumenter.cpp:175]: so basically keep the logic as is and rename flag wit a prefix: like pick_im -> no_pick_im?

Comment (cbielow) [reply doc/doxygen/parameters/TOPPDocumenter.cpp:175]: yes, I prefer `postive` names, i.e. `use_raw_peaks`, but that's a matter of taste
